export const LANGS = [
  "en","zh","zh-tw","es","hi","ar","bn","pt","ru","ja","de","fr","ko","it","tr","vi","id","th","nl","pl","uk",
] as const;

export type Lang = (typeof LANGS)[number];

export const LANG_LABELS: Record<Lang, string> = {
  en: "English", zh: "简体中文", "zh-tw": "繁體中文", es: "Español", hi: "हिन्दी", ar: "العربية",
  bn: "বাংলা", pt: "Português", ru: "Русский", ja: "日本語", de: "Deutsch", fr: "Français",
  ko: "한국어", it: "Italiano", tr: "Türkçe", vi: "Tiếng Việt", id: "Bahasa Indonesia",
  th: "ไทย", nl: "Nederlands", pl: "Polski", uk: "Українська",
};

export const STORAGE_LANG_KEY = "totpPreferredLanguage";

export function isLang(value: string): value is Lang {
  return (LANGS as readonly string[]).includes(value);
}

export function detectLang(navLang = typeof navigator !== "undefined" ? navigator.language : "en"): Lang {
  const lower = navLang.toLowerCase().replace("_", "-");
  if (lower.startsWith("zh-tw") || lower.startsWith("zh-hant") || lower === "zh-hk" || lower === "zh-mo") return "zh-tw";
  if (lower.startsWith("zh")) return "zh";
  const short = lower.split("-")[0];
  if (isLang(short)) return short;
  return "en";
}

export type UIKey =
  | "appName" | "tagline" | "skip" | "navHome" | "navTools" | "navGuides" | "navSitemap"
  | "navPrivacy" | "navAbout" | "lang" | "langAuto" | "genAdd" | "genName" | "genNamePh"
  | "genSecret" | "genSecretPh" | "genOptions" | "genDigits" | "genPeriod" | "genPeriodUnit"
  | "genAlgorithm" | "genPaste" | "genScan" | "genClear" | "genDelete" | "genCopied"
  | "genCopyFail" | "genWaiting" | "genInvalid" | "genLive" | "genSeconds" | "genScanNoApi"
  | "genScanNoCode" | "genScanOk" | "genPasteEmpty" | "genPasteNeedPerm" | "footerNote"
  | "footerRfc6238" | "footerRfc4226" | "footerKeyUri" | "footerNist" | "relatedTools"
  | "relatedGuides" | "faqTitle" | "matrixTitle" | "matrixCaption" | "notFound" | "notFoundBody"
  | "ctaTools" | "privacyBanner" | "copyHint" | "moreGuides" | "moreTools" | "moreDocs" | "dropHint" | "emptyCta"
  | "clockSkew" | "nextCode" | "hideSecret" | "showSecret" | "copyUri" | "showQr" | "copyCode" | "sessionHint"
  | "moreNav" | "pasteHint" | "localClock" | "camScan" | "camScanStop" | "moreActions" | "genCopiedNext"
  | "genNameQuiet" | "copyAllUri" | "uploadQr" | "clearVault" | "clearVaultConfirm" | "genScanSkipped";

type Pack = Record<Lang, string>;

function pack(en: string, rows: Partial<Record<Lang, string>>): Pack {
  const out = { en } as Pack;
  for (const lang of LANGS) {
    if (lang === "en") continue;
    out[lang] = rows[lang] ?? en;
  }
  return out;
}

const UI: Record<UIKey, Pack> = {
  appName: pack("Local TOTP", { zh: "本地 TOTP", "zh-tw": "本機 TOTP", es: "TOTP local", hi: "स्थानीय TOTP", ar: "TOTP المحلي", bn: "স্থানীয় TOTP", pt: "TOTP local", ru: "Локальный TOTP", ja: "ローカル TOTP", de: "Lokales TOTP", fr: "TOTP local", ko: "로컬 TOTP", it: "TOTP locale", tr: "Yerel TOTP", vi: "TOTP cục bộ", id: "TOTP lokal", th: "TOTP ในเครื่อง", nl: "Lokale TOTP", pl: "Lokalny TOTP", uk: "Локальний TOTP" }),
  tagline: pack("One-time codes in this browser. Secrets stay on this device.", { zh: "一次性验证码在本浏览器中计算。密钥不会离开这台设备。", "zh-tw": "一次性驗證碼在此瀏覽器中計算。金鑰不會離開這台裝置。", es: "Códigos de un solo uso en este navegador. El secreto no sale de este dispositivo.", hi: "इस ब्राउज़र में वन-टाइम कोड। सीक्रेट इस डिवाइस पर ही रहता है।", ar: "رموز لمرة واحدة في هذا المتصفح. يبقى السر على هذا الجهاز.", bn: "এই ব্রাউজারে একবার-ব্যবহার্য কোড। সিক্রেট এই ডিভাইসেই থাকে।", pt: "Códigos de uso único neste navegador. O segredo permanece neste dispositivo.", ru: "Одноразовые коды в этом браузере. Секрет остаётся на устройстве.", ja: "このブラウザでワンタイムコードを生成します。秘密鍵はこの端末から出ません。", de: "Einmalcodes in diesem Browser. Das Geheimnis bleibt auf diesem Gerät.", fr: "Codes à usage unique dans ce navigateur. Le secret reste sur cet appareil.", ko: "이 브라우저에서 일회용 코드를 만듭니다. 비밀 키는 이 기기를 떠나지 않습니다.", it: "Codici monouso in questo browser. Il segreto resta su questo dispositivo.", tr: "Tek kullanımlık kodlar bu tarayıcıda. Gizli anahtar bu cihazda kalır.", vi: "Mã một lần ngay trong trình duyệt. Bí mật không rời khỏi thiết bị này.", id: "Kode sekali pakai di browser ini. Rahasia tetap di perangkat ini.", th: "รหัสครั้งเดียวในเบราว์เซอร์นี้ ความลับไม่ได้ออกจากเครื่องนี้", nl: "Eenmalige codes in deze browser. Het geheim blijft op dit apparaat.", pl: "Kody jednorazowe w tej przeglądarce. Sekret zostaje na tym urządzeniu.", uk: "Одноразові коди в цьому браузері. Секрет лишається на пристрої." }),
  skip: pack("Skip to content", { zh: "跳到正文", "zh-tw": "跳到主要內容", es: "Saltar al contenido", hi: "सामग्री पर जाएँ", ar: "تخطٍ إلى المحتوى", bn: "কন্টেন্টে যান", pt: "Saltar para o conteúdo", ru: "К содержимому", ja: "本文へスキップ", de: "Zum Inhalt springen", fr: "Aller au contenu", ko: "본문으로 건너뛰기", it: "Salta al contenuto", tr: "İçeriğe geç", vi: "Bỏ qua tới nội dung", id: "Lewati ke konten", th: "ข้ามไปเนื้อหา", nl: "Naar inhoud", pl: "Przejdź do treści", uk: "До змісту" }),
  navHome: pack("Home", { zh: "首页", "zh-tw": "首頁", es: "Inicio", hi: "होम", ar: "الرئيسية", bn: "হোম", pt: "Início", ru: "Главная", ja: "ホーム", de: "Start", fr: "Accueil", ko: "홈", it: "Home", tr: "Ana sayfa", vi: "Trang chủ", id: "Beranda", th: "หน้าแรก", nl: "Home", pl: "Start", uk: "Головна" }),
  navTools: pack("Tools", { zh: "工具", "zh-tw": "工具", es: "Herramientas", hi: "टूल्स", ar: "أدوات", bn: "টুল", pt: "Ferramentas", ru: "Инструменты", ja: "ツール", de: "Werkzeuge", fr: "Outils", ko: "도구", it: "Strumenti", tr: "Araçlar", vi: "Công cụ", id: "Alat", th: "เครื่องมือ", nl: "Hulpmiddelen", pl: "Narzędzia", uk: "Інструменти" }),
  navGuides: pack("Guides", { zh: "指南", "zh-tw": "指南", es: "Guías", hi: "गाइड", ar: "أدلة", bn: "গাইড", pt: "Guias", ru: "Справки", ja: "ガイド", de: "Leitfäden", fr: "Guides", ko: "가이드", it: "Guide", tr: "Rehberler", vi: "Hướng dẫn", id: "Panduan", th: "คู่มือ", nl: "Gidsen", pl: "Poradniki", uk: "Довідки" }),
  navSitemap: pack("Site map", { zh: "网站地图", "zh-tw": "網站地圖", es: "Mapa del sitio", hi: "साइट मैप", ar: "خريطة الموقع", bn: "সাইট ম্যাপ", pt: "Mapa do site", ru: "Карта сайта", ja: "サイトマップ", de: "Sitemap", fr: "Plan du site", ko: "사이트맵", it: "Mappa del sito", tr: "Site haritası", vi: "Sơ đồ trang", id: "Peta situs", th: "แผนผังเว็บ", nl: "Sitemap", pl: "Mapa witryny", uk: "Мапа сайту" }),
  navPrivacy: pack("Privacy", { zh: "隐私", "zh-tw": "隱私", es: "Privacidad", hi: "गोपनीयता", ar: "الخصوصية", bn: "গোপনীয়তা", pt: "Privacidade", ru: "Конфиденциальность", ja: "プライバシー", de: "Datenschutz", fr: "Confidentialité", ko: "개인정보", it: "Privacy", tr: "Gizlilik", vi: "Quyền riêng tư", id: "Privasi", th: "ความเป็นส่วนตัว", nl: "Privacy", pl: "Prywatność", uk: "Приватність" }),
  navAbout: pack("About", { zh: "关于", "zh-tw": "關於", es: "Acerca de", hi: "परिचय", ar: "حول", bn: "সম্পর্কে", pt: "Sobre", ru: "О сайте", ja: "このサイト", de: "Über", fr: "À propos", ko: "소개", it: "Informazioni", tr: "Hakkında", vi: "Giới thiệu", id: "Tentang", th: "เกี่ยวกับ", nl: "Over", pl: "O stronie", uk: "Про сайт" }),
  lang: pack("Language", { zh: "语言", "zh-tw": "語言", es: "Idioma", hi: "भाषा", ar: "اللغة", bn: "ভাষা", pt: "Idioma", ru: "Язык", ja: "言語", de: "Sprache", fr: "Langue", ko: "언어", it: "Lingua", tr: "Dil", vi: "Ngôn ngữ", id: "Bahasa", th: "ภาษา", nl: "Taal", pl: "Język", uk: "Мова" }),
  langAuto: pack("Auto", { zh: "自动", "zh-tw": "自動", es: "Auto", hi: "स्वतः", ar: "تلقائي", bn: "স্বয়ংক্রিয়", pt: "Auto", ru: "Авто", ja: "自動", de: "Auto", fr: "Auto", ko: "자동", it: "Auto", tr: "Otomatik", vi: "Tự động", id: "Otomatis", th: "อัตโนมัติ", nl: "Auto", pl: "Auto", uk: "Авто" }),
  genAdd: pack("+ Add generator", { zh: "+ 添加生成器", "zh-tw": "+ 新增產生器", es: "+ Añadir generador", hi: "+ जनरेटर जोड़ें", ar: "+ إضافة مولّد", bn: "+ জেনারেটর যোগ করুন", pt: "+ Adicionar gerador", ru: "+ Добавить генератор", ja: "+ ジェネレーターを追加", de: "+ Generator hinzufügen", fr: "+ Ajouter un générateur", ko: "+ 생성기 추가", it: "+ Aggiungi generatore", tr: "+ Üreteç ekle", vi: "+ Thêm bộ tạo", id: "+ Tambah generator", th: "+ เพิ่มตัวสร้าง", nl: "+ Generator toevoegen", pl: "+ Dodaj generator", uk: "+ Додати генератор" }),
  genName: pack("Account name (optional)", { zh: "账户名称（可选）", "zh-tw": "帳戶名稱（選填）", es: "Nombre de cuenta (opcional)", hi: "खाता नाम (वैकल्पिक)", ar: "اسم الحساب (اختياري)", bn: "অ্যাকাউন্টের নাম (ঐচ্ছিক)", pt: "Nome da conta (opcional)", ru: "Имя учётки (необязательно)", ja: "アカウント名（任意）", de: "Kontoname (optional)", fr: "Nom du compte (facultatif)", ko: "계정 이름 (선택)", it: "Nome account (opzionale)", tr: "Hesap adı (isteğe bağlı)", vi: "Tên tài khoản (tuỳ chọn)", id: "Nama akun (opsional)", th: "ชื่อบัญชี (ไม่บังคับ)", nl: "Accountnaam (optioneel)", pl: "Nazwa konta (opcjonalnie)", uk: "Назва обліковки (необов’язково)" }),
  genNamePh: pack("e.g. mailbox or work SSO", { zh: "例如邮箱或公司 SSO", "zh-tw": "例如信箱或公司 SSO", es: "p. ej. correo o SSO de trabajo", hi: "जैसे मेलबॉक्स या कार्य SSO", ar: "مثال: البريد أو SSO للعمل", bn: "যেমন মেইলবক্স বা কাজের SSO", pt: "ex.: e-mail ou SSO do trabalho", ru: "например почта или рабочий SSO", ja: "例: メールや社内 SSO", de: "z. B. Postfach oder Firmen-SSO", fr: "ex. boîte mail ou SSO professionnel", ko: "예: 메일함 또는 회사 SSO", it: "es. casella o SSO di lavoro", tr: "ör. posta veya iş SSO", vi: "vd. hộp thư hoặc SSO công việc", id: "mis. kotak surat atau SSO kerja", th: "เช่น อีเมลหรือ SSO ที่ทำงาน", nl: "bijv. mailbox of werk-SSO", pl: "np. skrzynka lub SSO firmowe", uk: "напр. пошта чи робочий SSO" }),
  genSecret: pack("Setup key", { zh: "设置密钥", "zh-tw": "設定金鑰", es: "Clave de configuración", hi: "सेटअप कुंजी", ar: "مفتاح الإعداد", bn: "সেটআপ কী", pt: "Chave de configuração", ru: "Ключ настройки", ja: "セットアップキー", de: "Setup-Schlüssel", fr: "Clé de configuration", ko: "설정 키", it: "Chiave di configurazione", tr: "Kurulum anahtarı", vi: "Khóa thiết lập", id: "Kunci penyiapan", th: "คีย์ตั้งค่า", nl: "Setupsleutel", pl: "Klucz konfiguracji", uk: "Ключ налаштування" }),
  genSecretPh: pack("Base32 secret or otpauth:// URI", { zh: "Base32 密钥或 otpauth:// 链接", "zh-tw": "Base32 金鑰或 otpauth:// 連結", es: "Secreto Base32 o URI otpauth://", hi: "Base32 सीक्रेट या otpauth:// URI", ar: "سر Base32 أو رابط otpauth://", bn: "Base32 সিক্রেট বা otpauth:// URI", pt: "Segredo Base32 ou URI otpauth://", ru: "Секрет Base32 или URI otpauth://", ja: "Base32 シークレットまたは otpauth:// URI", de: "Base32-Geheimnis oder otpauth://-URI", fr: "Secret Base32 ou URI otpauth://", ko: "Base32 비밀 또는 otpauth:// URI", it: "Segreto Base32 o URI otpauth://", tr: "Base32 gizli anahtar veya otpauth:// URI", vi: "Bí mật Base32 hoặc URI otpauth://", id: "Rahasia Base32 atau URI otpauth://", th: "ความลับ Base32 หรือ URI otpauth://", nl: "Base32-geheim of otpauth://-URI", pl: "Sekret Base32 lub URI otpauth://", uk: "Секрет Base32 або URI otpauth://" }),
  genOptions: pack("TOTP options", { zh: "TOTP 选项", "zh-tw": "TOTP 選項", es: "Opciones TOTP", hi: "TOTP विकल्प", ar: "خيارات TOTP", bn: "TOTP অপশন", pt: "Opções TOTP", ru: "Параметры TOTP", ja: "TOTP オプション", de: "TOTP-Optionen", fr: "Options TOTP", ko: "TOTP 옵션", it: "Opzioni TOTP", tr: "TOTP seçenekleri", vi: "Tuỳ chọn TOTP", id: "Opsi TOTP", th: "ตัวเลือก TOTP", nl: "TOTP-opties", pl: "Opcje TOTP", uk: "Параметри TOTP" }),
  genDigits: pack("Digits", { zh: "位数", "zh-tw": "位數", es: "Dígitos", hi: "अंक", ar: "أرقام", bn: "অঙ্ক", pt: "Dígitos", ru: "Знаки", ja: "桁数", de: "Stellen", fr: "Chiffres", ko: "자릿수", it: "Cifre", tr: "Basamak", vi: "Số chữ số", id: "Digit", th: "หลัก", nl: "Cijfers", pl: "Cyfry", uk: "Цифри" }),
  genPeriod: pack("Period", { zh: "周期", "zh-tw": "週期", es: "Periodo", hi: "अवधि", ar: "الفترة", bn: "পিরিয়ড", pt: "Período", ru: "Период", ja: "周期", de: "Periode", fr: "Période", ko: "주기", it: "Periodo", tr: "Periyot", vi: "Chu kỳ", id: "Periode", th: "คาบเวลา", nl: "Periode", pl: "Okres", uk: "Період" }),
  genPeriodUnit: pack("s", { zh: "秒", "zh-tw": "秒", ja: "秒", ko: "초", ar: "ث", ru: "с", uk: "с", th: "วินาที", hi: "से", bn: "সে", tr: "sn", id: "d" }),
  genAlgorithm: pack("Algorithm", { zh: "算法", "zh-tw": "演算法", es: "Algoritmo", hi: "एल्गोरिदम", ar: "الخوارزمية", bn: "অ্যালগরিদম", pt: "Algoritmo", ru: "Алгоритм", ja: "アルゴリズム", de: "Algorithmus", fr: "Algorithme", ko: "알고리즘", it: "Algoritmo", tr: "Algoritma", vi: "Thuật toán", id: "Algoritma", th: "อัลกอริทึม", nl: "Algoritme", pl: "Algorytm", uk: "Алгоритм" }),
  genPaste: pack("Paste", { zh: "粘贴", "zh-tw": "貼上", es: "Pegar", hi: "चिपकाएँ", ar: "لصق", bn: "পেস্ট", pt: "Colar", ru: "Вставить", ja: "貼り付け", de: "Einfügen", fr: "Coller", ko: "붙여넣기", it: "Incolla", tr: "Yapıştır", vi: "Dán", id: "Tempel", th: "วาง", nl: "Plakken", pl: "Wklej", uk: "Вставити" }),
  genScan: pack("Scan QR image", { zh: "扫描二维码图片", "zh-tw": "掃描 QR 圖片", es: "Escanear imagen QR", hi: "QR छवि स्कैन करें", ar: "مسح صورة QR", bn: "QR ছবি স্ক্যান", pt: "Ler imagem QR", ru: "Сканировать QR-изображение", ja: "QR 画像を読み取る", de: "QR-Bild scannen", fr: "Lire une image QR", ko: "QR 이미지 스캔", it: "Scansiona immagine QR", tr: "QR görselini tara", vi: "Quét ảnh QR", id: "Pindai gambar QR", th: "สแกนรูป QR", nl: "QR-afbeelding scannen", pl: "Skanuj obraz QR", uk: "Сканувати QR-зображення" }),
  genClear: pack("Clear", { zh: "清除", "zh-tw": "清除", es: "Borrar", hi: "साफ़ करें", ar: "مسح", bn: "মুছুন", pt: "Limpar", ru: "Очистить", ja: "クリア", de: "Leeren", fr: "Effacer", ko: "지우기", it: "Cancella", tr: "Temizle", vi: "Xóa", id: "Hapus", th: "ล้าง", nl: "Wissen", pl: "Wyczyść", uk: "Очистити" }),
  genDelete: pack("Remove generator", { zh: "删除生成器", "zh-tw": "移除產生器", es: "Quitar generador", hi: "जनरेटर हटाएँ", ar: "إزالة المولّد", bn: "জেনারেটর সরান", pt: "Remover gerador", ru: "Удалить генератор", ja: "ジェネレーターを削除", de: "Generator entfernen", fr: "Supprimer le générateur", ko: "생성기 제거", it: "Rimuovi generatore", tr: "Üreteci kaldır", vi: "Xóa bộ tạo", id: "Hapus generator", th: "ลบตัวสร้าง", nl: "Generator verwijderen", pl: "Usuń generator", uk: "Прибрати генератор" }),
  genCopied: pack("Copied {code}", { zh: "已复制 {code}", "zh-tw": "已複製 {code}", es: "Copiado al portapapeles", hi: "क्लिपबोर्ड पर कॉपी हुआ", ar: "تم النسخ إلى الحافظة", bn: "ক্লিপবোর্ডে কপি হয়েছে", pt: "Copiado para a área de transferência", ru: "Скопировано в буфер", ja: "クリップボードにコピーしました", de: "In die Zwischenablage kopiert", fr: "Copié dans le presse-papiers", ko: "클립보드에 복사됨", it: "Copiato negli appunti", tr: "Panoya kopyalandı", vi: "Đã sao chép", id: "Disalin ke papan klip", th: "คัดลอกแล้ว", nl: "Gekopieerd naar klembord", pl: "Skopiowano do schowka", uk: "Скопійовано в буфер" }),
  genCopyFail: pack("Could not copy", { zh: "无法复制", "zh-tw": "無法複製", es: "No se pudo copiar", hi: "कॉपी नहीं हो सका", ar: "تعذّر النسخ", bn: "কপি করা যায়নি", pt: "Não foi possível copiar", ru: "Не удалось скопировать", ja: "コピーできませんでした", de: "Kopieren fehlgeschlagen", fr: "Copie impossible", ko: "복사할 수 없음", it: "Copia non riuscita", tr: "Kopyalanamadı", vi: "Không sao chép được", id: "Tidak bisa menyalin", th: "คัดลอกไม่ได้", nl: "Kopiëren mislukt", pl: "Nie udało się skopiować", uk: "Не вдалося скопіювати" }),
  genWaiting: pack("Enter a setup key to generate codes", { zh: "输入设置密钥以生成验证码", "zh-tw": "輸入設定金鑰以產生驗證碼", es: "Introduce una clave para generar códigos", hi: "कोड बनाने के लिए सेटअप कुंजी दर्ज करें", ar: "أدخل مفتاح الإعداد لإنشاء الرموز", bn: "কোড তৈরি করতে সেটআপ কী লিখুন", pt: "Introduza uma chave para gerar códigos", ru: "Введите ключ, чтобы получить коды", ja: "セットアップキーを入力するとコードが生成されます", de: "Setup-Schlüssel eingeben, um Codes zu erzeugen", fr: "Saisissez une clé pour générer des codes", ko: "코드를 만들려면 설정 키를 입력하세요", it: "Inserisci una chiave per generare i codici", tr: "Kod üretmek için kurulum anahtarı girin", vi: "Nhập khóa thiết lập để tạo mã", id: "Masukkan kunci penyiapan untuk membuat kode", th: "ใส่คีย์ตั้งค่าเพื่อสร้างรหัส", nl: "Voer een setupsleutel in om codes te maken", pl: "Wpisz klucz, aby wygenerować kody", uk: "Введіть ключ, щоб отримати коди" }),
  genInvalid: pack("That setup key is not valid Base32", { zh: "该设置密钥不是有效的 Base32", "zh-tw": "此設定金鑰不是有效的 Base32", es: "Esa clave no es Base32 válido", hi: "यह सेटअप कुंजी मान्य Base32 नहीं है", ar: "مفتاح الإعداد ليس Base32 صالحًا", bn: "সেটআপ কীটি বৈধ Base32 নয়", pt: "Essa chave não é Base32 válido", ru: "Ключ не является корректным Base32", ja: "このセットアップキーは有効な Base32 ではありません", de: "Dieser Setup-Schlüssel ist kein gültiges Base32", fr: "Cette clé n’est pas du Base32 valide", ko: "설정 키가 올바른 Base32가 아닙니다", it: "Questa chiave non è Base32 valido", tr: "Bu kurulum anahtarı geçerli Base32 değil", vi: "Khóa thiết lập không phải Base32 hợp lệ", id: "Kunci itu bukan Base32 yang valid", th: "คีย์นี้ไม่ใช่ Base32 ที่ถูกต้อง", nl: "Die setupsleutel is geen geldige Base32", pl: "Ten klucz nie jest poprawnym Base32", uk: "Ключ не є коректним Base32" }),
  genLive: pack("Code is live", { zh: "验证码有效", "zh-tw": "驗證碼有效", es: "El código está activo", hi: "कोड सक्रिय है", ar: "الرمز فعّال", bn: "কোড সক্রিয়", pt: "O código está ativo", ru: "Код действует", ja: "コードは有効です", de: "Code ist aktuell", fr: "Le code est actif", ko: "코드가 유효합니다", it: "Il codice è attivo", tr: "Kod geçerli", vi: "Mã đang hiệu lực", id: "Kode aktif", th: "รหัสใช้งานได้", nl: "Code is actief", pl: "Kod jest aktualny", uk: "Код чинний" }),
  genSeconds: pack("{n}s remaining", { zh: "剩余 {n} 秒", "zh-tw": "剩餘 {n} 秒", es: "{n}s restantes", hi: "{n} से शेष", ar: "متبقٍ {n} ث", bn: "{n} সে বাকি", pt: "{n}s restantes", ru: "осталось {n} с", ja: "残り {n} 秒", de: "noch {n}s", fr: "{n}s restantes", ko: "{n}초 남음", it: "{n}s rimanenti", tr: "{n} sn kaldı", vi: "còn {n}s", id: "{n}d tersisa", th: "เหลือ {n} วินาที", nl: "nog {n}s", pl: "pozostało {n}s", uk: "лишилось {n} с" }),
  genScanNoApi: pack("This browser cannot decode QR images (BarcodeDetector is missing). Paste the setup key instead.", { zh: "当前浏览器无法解码二维码图片（缺少 BarcodeDetector）。请改为粘贴设置密钥。", "zh-tw": "目前瀏覽器無法解碼 QR 圖片（缺少 BarcodeDetector）。請改為貼上設定金鑰。", es: "Este navegador no puede leer imágenes QR (falta BarcodeDetector). Pegue la clave.", hi: "यह ब्राउज़र QR छवियाँ नहीं पढ़ सकता (BarcodeDetector नहीं है)। कुंजी चिपकाएँ।", ar: "لا يستطيع هذا المتصفح قراءة صور QR (BarcodeDetector غير متوفر). الصق المفتاح بدلًا من ذلك.", bn: "এই ব্রাউজার QR ছবি পড়তে পারে না (BarcodeDetector নেই)। কী পেস্ট করুন।", pt: "Este navegador não lê imagens QR (sem BarcodeDetector). Cole a chave.", ru: "Браузер не умеет читать QR (нет BarcodeDetector). Вставьте ключ.", ja: "このブラウザは QR 画像を解読できません（BarcodeDetector なし）。キーを貼り付けてください。", de: "Dieser Browser kann QR-Bilder nicht lesen (kein BarcodeDetector). Schlüssel einfügen.", fr: "Ce navigateur ne lit pas les images QR (pas de BarcodeDetector). Collez la clé.", ko: "이 브라우저는 QR 이미지를 읽지 못합니다(BarcodeDetector 없음). 키를 붙여 넣으세요.", it: "Questo browser non legge immagini QR (manca BarcodeDetector). Incolla la chiave.", tr: "Bu tarayıcı QR görsellerini okuyamıyor (BarcodeDetector yok). Anahtarı yapıştırın.", vi: "Trình duyệt không đọc được ảnh QR (thiếu BarcodeDetector). Hãy dán khóa.", id: "Browser ini tidak bisa membaca gambar QR (tidak ada BarcodeDetector). Tempel kuncinya.", th: "เบราว์เซอร์นี้ถอดรหัสรูป QR ไม่ได้ (ไม่มี BarcodeDetector) ให้วางคีย์แทน", nl: "Deze browser kan geen QR-beelden lezen (geen BarcodeDetector). Plak de sleutel.", pl: "Ta przeglądarka nie odczyta obrazu QR (brak BarcodeDetector). Wklej klucz.", uk: "Браузер не читає QR-зображення (немає BarcodeDetector). Вставте ключ." }),
  genScanNoCode: pack("No QR code found in that image.", { zh: "图片中未找到二维码。", "zh-tw": "圖片中找不到 QR 碼。", es: "No se encontró un código QR en esa imagen.", hi: "उस छवि में QR कोड नहीं मिला।", ar: "لم يُعثر على رمز QR في تلك الصورة.", bn: "সেই ছবিতে QR কোড পাওয়া যায়নি।", pt: "Nenhum código QR nessa imagem.", ru: "QR-код на изображении не найден.", ja: "その画像に QR コードは見つかりませんでした。", de: "In diesem Bild wurde kein QR-Code gefunden.", fr: "Aucun code QR dans cette image.", ko: "해당 이미지에서 QR 코드를 찾지 못했습니다.", it: "Nessun codice QR in quell’immagine.", tr: "Bu görselde QR kod bulunamadı.", vi: "Không thấy mã QR trong ảnh đó.", id: "Tidak ada kode QR pada gambar itu.", th: "ไม่พบคิวอาร์ในรูปนั้น", nl: "Geen QR-code in die afbeelding.", pl: "Nie znaleziono kodu QR na tym obrazie.", uk: "QR-код на зображенні не знайдено." }),
  genScanOk: pack("Read QR payload.", { zh: "已读取二维码内容。", "zh-tw": "已讀取 QR 內容。", es: "Contenido QR leído.", hi: "QR सामग्री पढ़ी गई।", ar: "تم قراءة محتوى QR.", bn: "QR পেলোড পড়া হয়েছে।", pt: "Conteúdo QR lido.", ru: "Содержимое QR прочитано.", ja: "QR の内容を読み取りました。", de: "QR-Inhalt gelesen.", fr: "Contenu QR lu.", ko: "QR 내용을 읽었습니다.", it: "Contenuto QR letto.", tr: "QR içeriği okundu.", vi: "Đã đọc nội dung QR.", id: "Isi QR dibaca.", th: "อ่านข้อมูล QR แล้ว", nl: "QR-inhoud gelezen.", pl: "Odczytano zawartość QR.", uk: "Вміст QR прочитано." }),
  genPasteEmpty: pack("Clipboard was empty.", { zh: "剪贴板是空的。", "zh-tw": "剪貼簿是空的。", es: "El portapapeles estaba vacío.", hi: "क्लिपबोर्ड खाली था।", ar: "الحافظة فارغة.", bn: "ক্লিপবোর্ড খালি ছিল।", pt: "A área de transferência estava vazia.", ru: "Буфер обмена пуст.", ja: "クリップボードが空でした。", de: "Zwischenablage war leer.", fr: "Le presse-papiers était vide.", ko: "클립보드가 비어 있습니다.", it: "Gli appunti erano vuoti.", tr: "Pano boştu.", vi: "Clipboard trống.", id: "Papan klip kosong.", th: "คลิปบอร์ดว่าง", nl: "Klembord was leeg.", pl: "Schowek był pusty.", uk: "Буфер обміну порожній." }),
  genPasteNeedPerm: pack("Clipboard permission is required to paste.", { zh: "粘贴需要剪贴板权限。", "zh-tw": "貼上需要剪貼簿權限。", es: "Se necesita permiso del portapapeles para pegar.", hi: "पेस्ट करने के लिए क्लिपबोर्ड अनुमति चाहिए।", ar: "يلزم إذن الحافظة للصق.", bn: "পেস্ট করতে ক্লিপবোর্ড অনুমতি লাগে।", pt: "É necessária permissão da área de transferência.", ru: "Для вставки нужно разрешение буфера.", ja: "貼り付けにはクリップボードの許可が必要です。", de: "Zum Einfügen ist eine Zwischenablage-Berechtigung nötig.", fr: "L’autorisation du presse-papiers est requise.", ko: "붙여넣으려면 클립보드 권한이 필요합니다.", it: "Serve il permesso degli appunti per incollare.", tr: "Yapıştırmak için pano izni gerekir.", vi: "Cần quyền clipboard để dán.", id: "Izin papan klip diperlukan untuk menempel.", th: "ต้องอนุญาตคลิปบอร์ดจึงจะวางได้", nl: "Toestemming voor het klembord is nodig om te plakken.", pl: "Do wklejenia potrzebne jest uprawnienie do schowka.", uk: "Для вставлення потрібен дозвіл буфера." }),
  footerNote: pack("Local-first TOTP. No accounts, no ads. Secrets stay in this browser and never go to a server.", { zh: "本地优先的 TOTP。无账号、无广告。密钥只留在本浏览器，不会上传服务器。", "zh-tw": "本機優先的 TOTP。無帳號、無廣告。金鑰只留在本瀏覽器，不會上傳伺服器。" }),
  footerRfc6238: pack("RFC 6238", {}),
  footerRfc4226: pack("RFC 4226", {}),
  footerKeyUri: pack("Google Key URI format", { zh: "Google Key URI 格式", "zh-tw": "Google Key URI 格式", es: "Formato Key URI de Google", hi: "Google Key URI प्रारूप", ar: "تنسيق Google Key URI", bn: "Google Key URI ফরম্যাট", pt: "Formato Key URI do Google", ru: "Формат Google Key URI", ja: "Google Key URI 形式", de: "Google Key-URI-Format", fr: "Format Key URI Google", ko: "Google Key URI 형식", it: "Formato Key URI Google", tr: "Google Key URI biçimi", vi: "Định dạng Google Key URI", id: "Format Google Key URI", th: "รูปแบบ Google Key URI", nl: "Google Key URI-indeling", pl: "Format Google Key URI", uk: "Формат Google Key URI" }),
  footerNist: pack("NIST SP 800-63B", {}),
  relatedTools: pack("Related tools", { zh: "相关工具", "zh-tw": "相關工具", es: "Herramientas relacionadas", hi: "संबंधित टूल्स", ar: "أدوات ذات صلة", bn: "সম্পর্কিত টুল", pt: "Ferramentas relacionadas", ru: "Смежные инструменты", ja: "関連ツール", de: "Verwandte Werkzeuge", fr: "Outils associés", ko: "관련 도구", it: "Strumenti correlati", tr: "İlgili araçlar", vi: "Công cụ liên quan", id: "Alat terkait", th: "เครื่องมือที่เกี่ยวข้อง", nl: "Gerelateerde hulpmiddelen", pl: "Powiązane narzędzia", uk: "Пов’язані інструменти" }),
  relatedGuides: pack("Related guides", { zh: "相关指南", "zh-tw": "相關指南", es: "Guías relacionadas", hi: "संबंधित गाइड", ar: "أدلة ذات صلة", bn: "সম্পর্কিত গাইড", pt: "Guias relacionadas", ru: "Смежные справки", ja: "関連ガイド", de: "Verwandte Leitfäden", fr: "Guides associés", ko: "관련 가이드", it: "Guide correlate", tr: "İlgili rehberler", vi: "Hướng dẫn liên quan", id: "Panduan terkait", th: "คู่มือที่เกี่ยวข้อง", nl: "Gerelateerde gidsen", pl: "Powiązane poradniki", uk: "Пов’язані довідки" }),
  faqTitle: pack("Questions", { zh: "常见问题", "zh-tw": "常見問題", es: "Preguntas", hi: "सवाल", ar: "أسئلة", bn: "প্রশ্ন", pt: "Perguntas", ru: "Вопросы", ja: "よくある質問", de: "Fragen", fr: "Questions", ko: "질문", it: "Domande", tr: "Sorular", vi: "Câu hỏi", id: "Pertanyaan", th: "คำถาม", nl: "Vragen", pl: "Pytania", uk: "Питання" }),
  matrixTitle: pack("Authenticator compatibility", { zh: "验证器兼容性", "zh-tw": "驗證器相容性", es: "Compatibilidad de autenticadores", hi: "प्रमाणक संगतता", ar: "توافق تطبيقات المصادقة", bn: "অথেন্টিকেটর সামঞ্জস্য", pt: "Compatibilidade de autenticadores", ru: "Совместимость приложений", ja: "認証アプリの互換性", de: "Authenticator-Kompatibilität", fr: "Compatibilité des applications", ko: "인증 앱 호환성", it: "Compatibilità authenticator", tr: "Kimlik doğrulayıcı uyumu", vi: "Tương thích ứng dụng xác thực", id: "Kompatibilitas authenticator", th: "ความเข้ากันได้ของแอปยืนยันตัวตน", nl: "Authenticator-compatibiliteit", pl: "Zgodność aplikacji", uk: "Сумісність автентифікаторів" }),
  matrixCaption: pack("Typical TOTP features in popular authenticator apps. Confirm with the vendor; apps change.", { zh: "常见验证器应用的典型 TOTP 能力。请以厂商说明为准，应用会更新。", "zh-tw": "常見驗證器應用的典型 TOTP 能力。請以廠商說明為準，應用會更新。", es: "Funciones TOTP típicas. Confirme con el proveedor; las apps cambian.", hi: "लोकप्रिय ऐप्स की सामान्य TOTP क्षमताएँ। विक्रेता से पुष्टि करें।", ar: "ميزات TOTP الشائعة. أكّد مع البائع؛ التطبيقات تتغير.", bn: "জনপ্রিয় অ্যাপের সাধারণ TOTP বৈশিষ্ট্য। বিক্রেতার সাথে নিশ্চিত করুন।", pt: "Recursos TOTP típicos. Confirme com o fornecedor; os apps mudam.", ru: "Типичные возможности TOTP. Уточняйте у вендора — приложения меняются.", ja: "一般的な認証アプリの TOTP 機能の目安です。ベンダーに確認してください。", de: "Typische TOTP-Funktionen. Beim Anbieter prüfen; Apps ändern sich.", fr: "Fonctions TOTP typiques. Vérifiez auprès de l’éditeur ; les apps évoluent.", ko: "인기 인증 앱의 일반적인 TOTP 기능입니다. 벤더 안내를 확인하세요.", it: "Funzioni TOTP tipiche. Confermare col fornitore; le app cambiano.", tr: "Popüler uygulamaların tipik TOTP özellikleri. Satıcıyla doğrulayın.", vi: "Tính năng TOTP điển hình. Hãy xác nhận với nhà cung cấp; ứng dụng thay đổi.", id: "Fitur TOTP tipikal. Konfirmasi ke vendor; aplikasi berubah.", th: "ฟีเจอร์ TOTP โดยทั่วไป โปรดยืนยันกับผู้ขาย แอปมีการเปลี่ยนแปลง", nl: "Typische TOTP-functies. Bevestig bij de leverancier; apps wijzigen.", pl: "Typowe funkcje TOTP. Potwierdź u dostawcy; aplikacje się zmieniają.", uk: "Типові можливості TOTP. Уточнюйте у постачальника — програми змінюються." }),
  notFound: pack("Page not found", { zh: "未找到页面", "zh-tw": "找不到頁面", es: "Página no encontrada", hi: "पृष्ठ नहीं मिला", ar: "الصفحة غير موجودة", bn: "পাতা পাওয়া যায়নি", pt: "Página não encontrada", ru: "Страница не найдена", ja: "ページが見つかりません", de: "Seite nicht gefunden", fr: "Page introuvable", ko: "페이지를 찾을 수 없음", it: "Pagina non trovata", tr: "Sayfa bulunamadı", vi: "Không tìm thấy trang", id: "Halaman tidak ditemukan", th: "ไม่พบหน้า", nl: "Pagina niet gevonden", pl: "Nie znaleziono strony", uk: "Сторінку не знайдено" }),
  notFoundBody: pack("That path is not a documented page. If it looks like a Base32 secret, it can open a generator instead.", { zh: "该路径不是站点页面。如果它看起来像 Base32 密钥，会改在生成器中打开。", "zh-tw": "此路徑不是網站頁面。若它看起來像 Base32 金鑰，會改在產生器中開啟。", es: "Esa ruta no es una página documentada. Si parece un secreto Base32, se abre un generador.", hi: "यह पथ कोई प्रलेखित पृष्ठ नहीं है। Base32 सीक्रेट लगने पर जनरेटर खुल सकता है।", ar: "هذا المسار ليس صفحة موثّقة. إن بدا كسر Base32 يمكن فتح مولّد بدلًا منه.", bn: "এই পাথ কোনো নথিভুক্ত পাতা নয়। Base32 সিক্রেট মনে হলে জেনারেটর খুলতে পারে।", pt: "Esse caminho não é uma página documentada. Se parecer um segredo Base32, abre um gerador.", ru: "Этот путь не страница сайта. Если это похоже на секрет Base32, откроется генератор.", ja: "このパスはサイトのページではありません。Base32 シークレットならジェネレーターを開きます。", de: "Dieser Pfad ist keine Dokumentationsseite. Sieht er nach einem Base32-Geheimnis aus, öffnet sich ein Generator.", fr: "Ce chemin n’est pas une page documentée. S’il ressemble à un secret Base32, un générateur s’ouvre.", ko: "이 경로는 문서화된 페이지가 아닙니다. Base32 비밀처럼 보이면 생성기가 열립니다.", it: "Questo percorso non è una pagina documentata. Se sembra un segreto Base32, si apre un generatore.", tr: "Bu yol belgelenmiş bir sayfa değil. Base32 sır gibi duruyorsa bir üreteç açılabilir.", vi: "Đường dẫn này không phải trang tài liệu. Nếu giống bí mật Base32, bộ tạo sẽ mở.", id: "Path ini bukan halaman terdokumentasi. Jika menyerupai rahasia Base32, generator bisa terbuka.", th: "เส้นทางนี้ไม่ใช่หน้าเอกสาร หากเหมือนความลับ Base32 จะเปิดตัวสร้างแทน", nl: "Dit pad is geen gedocumenteerde pagina. Lijkt het op een Base32-geheim, dan opent een generator.", pl: "Ta ścieżka nie jest stroną dokumentacji. Jeśli wygląda na sekret Base32, otworzy się generator.", uk: "Цей шлях не є сторінкою сайту. Якщо це схоже на секрет Base32, відкриється генератор." }),
  ctaTools: pack("Open a generator", { zh: "打开生成器", "zh-tw": "開啟產生器", es: "Abrir un generador", hi: "जनरेटर खोलें", ar: "افتح مولّدًا", bn: "জেনারেটর খুলুন", pt: "Abrir um gerador", ru: "Открыть генератор", ja: "ジェネレーターを開く", de: "Generator öffnen", fr: "Ouvrir un générateur", ko: "생성기 열기", it: "Apri un generatore", tr: "Üreteç aç", vi: "Mở bộ tạo", id: "Buka generator", th: "เปิดตัวสร้าง", nl: "Open een generator", pl: "Otwórz generator", uk: "Відкрити генератор" }),
  privacyBanner: pack("Codes are computed with Web Crypto in this browser. Secrets live in this browser's localStorage only; they never go to a server.", { zh: "验证码用本浏览器的 Web Crypto 计算。密钥只保存在本机 localStorage，不会上传到服务器。", "zh-tw": "驗證碼以本瀏覽器的 Web Crypto 計算。金鑰只保存在本機 localStorage，不會上傳到伺服器。" }),
  copyHint: pack("Click to copy", { zh: "点击复制", "zh-tw": "點一下複製", es: "Clic o Enter para copiar", hi: "कॉपी करने के लिए क्लिक या Enter", ar: "انقر أو اضغط Enter للنسخ", bn: "কপি করতে ক্লিক বা Enter", pt: "Clique ou Enter para copiar", ru: "Нажмите или Enter, чтобы скопировать", ja: "クリックまたは Enter でコピー", de: "Klicken oder Enter zum Kopieren", fr: "Cliquer ou Entrée pour copier", ko: "클릭 또는 Enter로 복사", it: "Clic o Invio per copiare", tr: "Kopyalamak için tıklayın veya Enter", vi: "Nhấp hoặc Enter để sao chép", id: "Klik atau Enter untuk menyalin", th: "คลิกหรือกด Enter เพื่อคัดลอก", nl: "Klik of Enter om te kopiëren", pl: "Kliknij lub Enter, aby skopiować", uk: "Клацніть або Enter, щоб скопіювати" }),
  moreGuides: pack("More guides", { zh: "更多指南", "zh-tw": "更多指南", es: "Más guías", hi: "और गाइड", ar: "المزيد من الأدلة", bn: "আরও গাইড", pt: "Mais guias", ru: "Ещё справки", ja: "その他のガイド", de: "Weitere Leitfäden", fr: "Plus de guides", ko: "더 많은 가이드", it: "Altre guide", tr: "Diğer rehberler", vi: "Thêm hướng dẫn", id: "Panduan lain", th: "คู่มือเพิ่มเติม", nl: "Meer gidsen", pl: "Więcej poradników", uk: "Більше довідок" }),
  moreTools: pack("More tools", { zh: "更多工具", "zh-tw": "更多工具", es: "Más herramientas", hi: "और टूल्स", ar: "المزيد من الأدوات", bn: "আরও টুল", pt: "Mais ferramentas", ru: "Ещё инструменты", ja: "その他のツール", de: "Weitere Werkzeuge", fr: "Plus d’outils", ko: "더 많은 도구", it: "Altri strumenti", tr: "Diğer araçlar", vi: "Thêm công cụ", id: "Alat lain", th: "เครื่องมือเพิ่มเติม", nl: "Meer hulpmiddelen", pl: "Więcej narzędzi", uk: "Більше інструментів" }),
  moreDocs: pack("Usage notes and FAQ", { zh: "使用说明与常见问题", "zh-tw": "使用說明與常見問題" }),
  dropHint: pack("Ctrl+V to paste a key, or drop a QR here", { zh: "Ctrl+V 粘贴密钥，或把二维码拖到这里", "zh-tw": "Ctrl+V 貼上金鑰，或把 QR 拖到這裡" }),
  emptyCta: pack("Paste your setup key", { zh: "粘贴设置密钥", "zh-tw": "貼上設定金鑰" }),
  clockSkew: pack("Clock", { zh: "时间校准" }),
  nextCode: pack("Next {code}", { zh: "下一组 {code}" }),
  hideSecret: pack("Hide", { zh: "隐藏" }),
  showSecret: pack("Show", { zh: "显示" }),
  copyUri: pack("Copy link", { zh: "复制链接" }),
  showQr: pack("Show QR", { zh: "显示二维码" }),
  copyCode: pack("Copy", { zh: "复制" }),
  sessionHint: pack("This browser keeps the keys on this device until you delete them.", { zh: "本浏览器会把密钥保存在这台设备上，直到你自行删除。" }),
  moreNav: pack("More", { zh: "更多", "zh-tw": "更多" }),
  pasteHint: pack("Ctrl+V to paste a key or QR screenshot, or drop a QR here", { zh: "Ctrl+V 粘贴密钥或二维码截图，或把二维码拖到这里", "zh-tw": "Ctrl+V 貼上金鑰或 QR 截圖，或把 QR 拖到這裡" }),
  localClock: pack("Local {time}", { zh: "本机 {time}", "zh-tw": "本機 {time}" }),
  camScan: pack("Scan with camera", { zh: "摄像头扫码", "zh-tw": "鏡頭掃碼" }),
  camScanStop: pack("Stop camera", { zh: "关闭摄像头", "zh-tw": "關閉鏡頭" }),
  moreActions: pack("More actions", { zh: "更多操作", "zh-tw": "更多操作" }),
  genCopiedNext: pack("Copied next {code}", { zh: "已复制下一组 {code}", "zh-tw": "已複製下一組 {code}" }),
  genNameQuiet: pack("Name (optional)", { zh: "名称（可选）" }),
  copyAllUri: pack("Copy all links", { zh: "复制全部链接" }),
  uploadQr: pack("Upload QR", { zh: "上传二维码" }),
  clearVault: pack("Clear device records", { zh: "清除本机记录" }),
  clearVaultConfirm: pack("Delete all setup keys saved in this browser?", { zh: "确定清除本机保存的全部设置密钥？" }),
  genScanSkipped: pack("Skipped a duplicate key.", { zh: "已跳过重复密钥。" }),
};

export function t(lang: Lang, key: UIKey, vars?: Record<string, string | number>): string {
  let s = UI[key][lang] || UI[key].en;
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      s = s.replaceAll(`{${k}}`, String(v));
    }
  }
  return s;
}

export function dirFor(lang: Lang): "rtl" | "ltr" {
  return lang === "ar" ? "rtl" : "ltr";
}
