import { tool } from "./tool-helper";

export const TOOL_ROUTES_B = [
  tool({
    path: "/totp-code-generator",
    titleEn: "TOTP code generator",
    titleZh: "TOTP 验证码生成器",
    titles: { "zh-tw": "TOTP 驗證碼產生器", es: "Generador de códigos TOTP", ja: "TOTP コード生成", de: "TOTP-Codegenerator", fr: "Générateur de codes TOTP", ko: "TOTP 코드 생성기" },
    descEn: "Show the current TOTP code for a setup key with a live countdown.",
    descZh: "根据设置密钥显示当前 TOTP 验证码并带实时倒计时。",
    h1En: "Codes appear only after the key decodes",
    h1Zh: "密钥解码成功后才显示验证码",
    introEn: "The large display stays at ------ until Base32 decoding succeeds. That avoids flashing a truncated HMAC of garbage input.",
    introZh: "在 Base32 解码成功前，大号显示保持为 ------，避免对垃圾输入的截断 HMAC 一闪而过。",
    bodyEn: "<p>Status text is a live region so screen readers hear when a new window starts. Copying is explicit: click or Enter, never a hidden network call.</p>",
    bodyZh: "<p>状态文本是 live region，读屏可以听到新时间窗开始。复制必须明确：点击或按 Enter，绝不会偷偷发起网络请求。</p>",
    q1e: "Why dashes?", a1e: "They mean 'no valid key yet', not a literal code of hyphens.",
    q2e: "Does copy include spaces?", a2e: "No. The clipboard gets the zero-padded digits only.",
    q3e: "Can I freeze a code?", a3e: "No. The spec wants the current time step. Screenshot quickly if a form is slow.",
    q1z: "为什么是短横线？", a1z: "表示还没有有效密钥，不是字面意义上的连字符验证码。",
    q2z: "复制会带空格吗？", a2z: "不会。剪贴板只有补零后的数字。",
    q3z: "能冻结一个码吗？", a3z: "不能。规范要求当前时间步。如果表单很慢，请尽快截图。",
  }),
  tool({
    path: "/2fa-code-generator",
    titleEn: "2FA code generator",
    titleZh: "2FA 验证码生成器",
    titles: { "zh-tw": "2FA 驗證碼產生器", es: "Generador de códigos 2FA", ja: "2FA コード生成", de: "2FA-Codegenerator", fr: "Générateur de codes 2FA", ko: "2FA 코드 생성기" },
    descEn: "Produce the 2FA code that login forms ask for from a local setup key.",
    descZh: "用本地设置密钥生成登录表单要的 2FA 验证码。",
    h1En: "Login forms want the current 2FA code, not the key",
    h1Zh: "登录表单要的是当前 2FA 验证码，不是密钥",
    introEn: "Never paste the setup key into a login field. Paste it here (or into an authenticator), then copy only the short code into the issuer's form.",
    introZh: "千万不要把设置密钥贴进登录框。把它贴在这里（或验证器里），再只把短码复制到发行方的表单。",
    bodyEn: "<p>If a site asks to 'scan a QR code' during enrollment, that step still belongs in a durable authenticator. Use this generator later if the phone is charging in another room.</p>",
    bodyZh: "<p>如果网站在登记时要求“扫描二维码”，那一步仍应放进可长期使用的验证器。之后如果手机在另一间房充电，再用这个生成器。</p>",
    q1e: "What if I typed the key into the login box?", a1e: "Cancel and use the short code instead. Rotate the 2FA key if you submitted the secret to the wrong field on a shared computer.",
    q2e: "Push notifications?", a2e: "Not supported. This is HMAC TOTP only.",
    q3e: "Work VPN prompts?", a3e: "If they are TOTP, yes. If they are proprietary tokens, no.",
    q1z: "如果我把密钥打进了登录框？", a1z: "取消并用短码。若在公用电脑上把密钥提交到错误字段，请轮换 2FA 密钥。",
    q2z: "支持推送通知吗？", a2z: "不支持。这里只有 HMAC TOTP。",
    q3z: "公司 VPN 提示呢？", a3z: "如果是 TOTP 就可以。如果是专有令牌则不行。",
  }),
  tool({
    path: "/authenticator-app-code-generator",
    titleEn: "Authenticator app code generator",
    titleZh: "验证器应用验证码生成器",
    titles: { "zh-tw": "驗證器應用驗證碼產生器", es: "Generador de códigos de app autenticadora", ja: "認証アプリのコード生成", de: "Authenticator-App-Codegenerator", fr: "Générateur de codes d’application", ko: "인증 앱 코드 생성기" },
    descEn: "Mimic an authenticator app's rotating code without installing one.",
    descZh: "无需安装应用，模拟验证器里滚动的验证码。",
    h1En: "Same math as an authenticator app, different container",
    h1Zh: "与验证器应用相同的数学，不同的容器",
    introEn: "Authenticator apps store keys and display TOTP. This page skips storage on purpose. You supply the key each session so a shared laptop does not keep it.",
    introZh: "验证器应用会保存密钥并显示 TOTP。本页故意不存储。每次会话由你提供密钥，避免共用笔记本留下它。",
    bodyEn: "<p>Feature parity stops at HMAC TOTP. Cloud backup, wearable unlock, and push approval live in vendor apps, not here.</p>",
    bodyZh: "<p>功能对等止于 HMAC TOTP。云备份、手表解锁和推送确认属于厂商应用，不在这里。</p>",
    q1e: "Will this replace Google Authenticator?", a1e: "Only as an emergency calculator. Keep a real authenticator for daily use.",
    q2e: "Can I import an Aegis JSON?", a2e: "Not as a file. Paste each otpauth URI or Base32 key into its own card.",
    q3e: "Does it work offline after first load?", a3e: "Yes, until you refresh without cache. It is a static bundle.",
    q1z: "这能替代 Google Authenticator 吗？", a1z: "只能当应急计算器。日常请保留真正的验证器。",
    q2z: "能导入 Aegis JSON 吗？", a2z: "不能当文件导入。把每条 otpauth 或 Base32 密钥贴进各自的卡片。",
    q3z: "首次加载后能离线用吗？", a3z: "可以，直到你在无缓存时刷新。这是静态打包。",
  }),
  tool({
    path: "/chatgpt-authenticator-app",
    titleEn: "ChatGPT authenticator setup (local TOTP helper)",
    titleZh: "ChatGPT 验证器设置（本地 TOTP 辅助）",
    titles: { "zh-tw": "ChatGPT 驗證器設定（本機 TOTP 輔助）", es: "Configuración del autenticador de ChatGPT", ja: "ChatGPT の認証アプリ設定", de: "ChatGPT-Authenticator-Einrichtung", fr: "Configuration authenticator ChatGPT", ko: "ChatGPT 인증 앱 설정" },
    descEn: "How official ChatGPT Security 2FA works, and when a local TOTP calculator helps.",
    descZh: "官方 ChatGPT Security 的 2FA 如何工作，以及何时需要本地 TOTP 计算器。",
    h1En: "ChatGPT 2FA uses your authenticator, not a fake ChatGPT app",
    h1Zh: "ChatGPT 的 2FA 用的是你的验证器，不是伪造的 ChatGPT 应用",
    introEn: "OpenAI lets you protect a ChatGPT account with an authenticator app through ChatGPT Settings → Security. You scan a QR (or type a setup key) into Google Authenticator, 1Password, Aegis, or similar. This website is not ChatGPT, not ChatGPT Atlas, and not an official OpenAI authenticator.",
    introZh: "OpenAI 允许通过 ChatGPT 设置 → 安全性，用验证器应用保护 ChatGPT 账户。你把二维码（或设置密钥）扫进 Google Authenticator、1Password、Aegis 等。本网站不是 ChatGPT，不是 ChatGPT Atlas，也不是官方 OpenAI 验证器。",
    bodyEn: "<p>Use the official ChatGPT app or website to start enrollment, view backup codes, and disable 2FA. A local TOTP helper is useful later: the phone is unavailable, you stored the setup key in a password manager, or you want to verify that a recovered Base32 string still produces codes before you risk a login. Paste that key below; do not type it into random third-party bots.</p><p>If ChatGPT shows an otpauth URI, paste the whole URI. This tool will read the secret, algorithm, digits, period, and name. Prefer the official in-app authenticator flow whenever the device that enrolled 2FA is still in your hands.</p>",
    bodyZh: "<p>请用官方 ChatGPT 应用或网站开始登记、查看备用码并关闭 2FA。本地 TOTP 辅助适合之后：手机不在身边、设置密钥在密码管理器里，或你想在冒险登录前确认恢复出的 Base32 仍能出码。把密钥贴到下方；不要打进随机第三方机器人。</p><p>如果 ChatGPT 显示 otpauth 链接，请整段粘贴。本工具会读取密钥、算法、位数、周期和名称。只要登记 2FA 的设备还在你手上，就优先走官方应用内流程。</p>",
    q1e: "Is this an official ChatGPT authenticator?", a1e: "No. It is an independent RFC 6238 calculator that can replay a setup key you already saved from ChatGPT Security.",
    q2e: "Where do I enable 2FA for ChatGPT?", a2e: "In the official ChatGPT product: Settings, then Security. Follow OpenAI's current enrollment screens there.",
    q3e: "What if I lost the phone and have no backup codes?", a3e: "Use OpenAI account recovery, not this page. A generator cannot reconstruct a key you never stored.",
    q1z: "这是官方 ChatGPT 验证器吗？", a1z: "不是。这是独立的 RFC 6238 计算器，可以重放你已从 ChatGPT Security 保存的设置密钥。",
    q2z: "在哪里为 ChatGPT 启用 2FA？", a2z: "在官方 ChatGPT 产品中：设置，然后是安全性。请按 OpenAI 当前的登记界面操作。",
    q3z: "手机丢了又没有备用码怎么办？", a3z: "走 OpenAI 账户恢复，而不是本页。生成器无法重建你从未保存过的密钥。",
  }),
];
