import { tool } from "./tool-helper";

export const TOOL_ROUTES_E = [
  tool({
    path: "/authenticator-qr-code-reader",
    titleEn: "Authenticator QR code reader",
    titleZh: "验证器二维码读取器",
    titles: { "zh-tw": "驗證器 QR 讀取器", es: "Lector de QR de autenticador", ja: "認証 QR リーダー", de: "Authenticator-QR-Leser", fr: "Lecteur QR authenticator", ko: "인증 QR 리더" },
    descEn: "Read authenticator QR images into independent generator cards.",
    descZh: "把验证器二维码图片读入独立的生成器卡片。",
    h1En: "One QR per card keeps accounts separate",
    h1Zh: "一张二维码对应一张卡片，账户互不混用",
    introEn: "Scan QR image attaches to the card that requested it. Add another generator before scanning a second account so names and keys do not overwrite each other.",
    introZh: "扫描二维码图片会作用于发起请求的那张卡片。扫描第二个账户前请先添加生成器，以免名称和密钥互相覆盖。",
    bodyEn: "<p>URL bootstrap only fills the first card, whether the secret arrived as a fragment, query, or path.</p>",
    bodyZh: "<p>无论密钥来自片段、查询还是路径，URL 引导只填充第一张卡片。</p>",
    q1e: "Can two cards tick independently?", a1e: "Yes. Periods can differ; the 1s timer refreshes all cards.",
    q2e: "Delete a card?", a2e: "The × control hides when only one card remains.",
    q3e: "Name source?", a3e: "Issuer or label from otpauth, otherwise you type it.",
    q1z: "两张卡片能独立走时吗？", a1z: "能。周期可以不同；1 秒定时器会刷新所有卡片。",
    q2z: "如何删除卡片？", a2z: "只剩一张时，× 按钮会隐藏。",
    q3z: "名称从哪来？", a3z: "otpauth 的发行方或标签，否则自行输入。",
  }),
  tool({
    path: "/authenticator-setup-key-to-code",
    titleEn: "Authenticator setup key to code",
    titleZh: "验证器设置密钥转验证码",
    titles: { "zh-tw": "驗證器設定金鑰轉驗證碼", es: "De clave de autenticador a código", ja: "セットアップキーからコードへ", de: "Setup-Schlüssel zu Code", fr: "Clé authenticator vers code", ko: "설정 키를 코드로" },
    descEn: "Convert an authenticator setup key into the current TOTP code.",
    descZh: "把验证器设置密钥转换成当前 TOTP 验证码。",
    h1En: "From setup key to digits in one tab",
    h1Zh: "在一个标签页里从设置密钥到数字",
    introEn: "Paste the setup key, watch dashes become digits, copy them into the login form. That is the entire loop this page optimizes.",
    introZh: "粘贴设置密钥，看着短横线变成数字，再复制到登录表单。这就是本页优化的整条回路。",
    bodyEn: "<p>If the issuer gave SHA-256, open TOTP options before you trust the first code. Wrong hash, right key, still a mismatch.</p>",
    bodyZh: "<p>如果发行方指定 SHA-256，请在相信第一组码之前打开 TOTP 选项。哈希错了，密钥对了，仍然对不上。</p>",
    q1e: "Leading spaces?", a1e: "Stripped during Base32 normalize.",
    q2e: "Unicode lookalikes?", a2e: "Rejected. Only ASCII A–Z and 2–7 after normalize.",
    q3e: "Empty paste?", a3e: "The status region says the clipboard was empty.",
    q1z: "前面有空格？", a1z: "Base32 规范化时会去掉。",
    q2z: "Unicode 形似字？", a2z: "拒绝。规范化后只接受 ASCII 的 A–Z 和 2–7。",
    q3z: "粘贴是空的？", a3z: "状态区会说明剪贴板是空的。",
  }),
  tool({
    path: "/mfa-token-generator",
    titleEn: "MFA token generator",
    titleZh: "MFA 令牌生成器",
    titles: { "zh-tw": "MFA 令牌產生器", es: "Generador de tokens MFA", ja: "MFA トークン生成", de: "MFA-Tokengenerator", fr: "Générateur de jeton MFA", ko: "MFA 토큰 생성기" },
    descEn: "Software MFA token codes from HMAC-SHA, not from a hardware serial.",
    descZh: "来自 HMAC-SHA 的软件 MFA 令牌码，不是硬件序列号。",
    h1En: "Call it a token if you like; the RFC still says TOTP",
    h1Zh: "你愿意叫令牌也行，RFC 仍然叫 TOTP",
    introEn: "MFA token is vendor vocabulary for the same 6 or 8 digit window. This generator implements the RFC, not a proprietary seed file.",
    introZh: "MFA 令牌是厂商对同一 6 位或 8 位时间窗的叫法。本生成器实现 RFC，而不是专有种子文件。",
    bodyEn: "<p>If your token has a battery and a button, you probably need the vendor tool. If enrollment showed Base32, you are in the right place.</p>",
    bodyZh: "<p>如果令牌有电池和按钮，你大概需要厂商工具。如果登记时出现 Base32，那你来对了。</p>",
    q1e: "PIV / smart cards?", a1e: "Out of scope.",
    q2e: "Seed files with %?", a2e: "Not parsed. Convert to Base32 or otpauth first.",
    q3e: "NIST SP 800-63B?", a3e: "That document discusses authenticator types. TOTP is a look-up secret; phishing-resistant AAL2 prefers hardware cryptographic authenticators.",
    q1z: "PIV / 智能卡？", a1z: "不在范围内。",
    q2z: "带 % 的种子文件？", a2z: "不解析。请先转成 Base32 或 otpauth。",
    q3z: "NIST SP 800-63B？", a3z: "该文档讨论认证器类型。TOTP 属于查找型密钥；抗钓鱼的 AAL2 更倾向硬件密码学认证器。",
  }),
  tool({
    path: "/base32-secret-totp",
    titleEn: "Base32 secret TOTP",
    titleZh: "Base32 密钥 TOTP",
    titles: { "zh-tw": "Base32 金鑰 TOTP", es: "TOTP con secreto Base32", ja: "Base32 シークレット TOTP", de: "Base32-Geheimnis-TOTP", fr: "TOTP secret Base32", ko: "Base32 비밀 TOTP" },
    descEn: "Strict Base32 (A–Z2–7) decoding into RFC 6238 codes.",
    descZh: "把严格的 Base32（A–Z2–7）解码为 RFC 6238 验证码。",
    h1En: "Invalid Base32 is a hard error, not a guess",
    h1Zh: "无效 Base32 会直接报错，而不是猜测",
    introEn: "Crockford Base32, hex, or Morse will not be auto-detected. The alphabet is RFC 4648. After normalize, length over 256 is rejected.",
    introZh: "不会自动识别 Crockford Base32、十六进制或摩尔斯。字母表是 RFC 4648。规范化后长度超过 256 会被拒绝。",
    bodyEn: "<p>The RFC 6238 demo keys also have Base32 spellings in rfc6238-test-vectors.json so you can paste them into this UI.</p>",
    bodyZh: "<p>RFC 6238 演示密钥在 rfc6238-test-vectors.json 里也有 Base32 写法，可以直接贴进本界面。</p>",
    q1e: "Why reject 0, 1, 8, 9?", a1e: "They are not in the RFC 4648 Base32 alphabet. They often indicate a typo.",
    q2e: "Binary secrets?", a2e: "Encode them as Base32 first, or use the ASCII RFC vectors only inside tests.",
    q3e: "Padding required?", a3e: "No. Padding is stripped if present.",
    q1z: "为什么拒绝 0、1、8、9？", a1z: "它们不在 RFC 4648 Base32 字母表中，常常表示打错。",
    q2z: "二进制密钥？", a2z: "请先编成 Base32，或仅在测试里使用 RFC 的 ASCII 向量。",
    q3z: "必须填充吗？", a3z: "不必。若有填充会被去掉。",
  }),
];
