import { tool } from "./tool-helper";

export const TOOL_ROUTES_G = [
  tool({
    path: "/2fa-secret-to-code",
    titleEn: "2FA secret to code",
    titleZh: "2FA 密钥转验证码",
    titles: { "zh-tw": "2FA 金鑰轉驗證碼", es: "Secreto 2FA a código", ja: "2FA シークレットからコード", de: "2FA-Geheimnis zu Code", fr: "Secret 2FA vers code", ko: "2FA 비밀을 코드로" },
    descEn: "Map a 2FA secret string to the current one-time code.",
    descZh: "把 2FA 密钥字符串映射为当前一次性验证码。",
    h1En: "Secret in, short code out, nothing in between stored",
    h1Zh: "密钥进、短码出，中间过程不存储",
    introEn: "Treat this as a function: Base32 secret plus clock plus parameters equals digits. Closing the tab is the destructor.",
    introZh: "把它看成一个函数：Base32 密钥加时钟加参数等于数字。关闭标签页就是析构。",
    bodyEn: "<p>Hash fragments are preferred. If you arrived with ?secret= or /YOURBASE32, the app rewrites to #secret= when possible.</p>",
    bodyZh: "<p>优先使用 hash 片段。如果你带着 ?secret= 或 /YOURBASE32 进来，应用会在可能时改写为 #secret=。</p>",
    q1e: "Will the rewrite drop other query params?", a1e: "Language and unrelated params stay; secret-like names are removed from the query.",
    q2e: "Path collision?", a2e: "Reserved routes always win over treating the path as Base32.",
    q3e: "Can I keep the query?", a3e: "You can, but fragments leak less to operators.",
    q1z: "改写会丢掉其他查询参数吗？", a1z: "语言和无关参数会保留；类似密钥的名字会从查询中移除。",
    q2z: "路径冲突？", a2z: "保留路由一定优先于把路径当成 Base32。",
    q3z: "能否保留查询？", a3z: "可以，但片段对运营方泄露更少。",
  }),
  tool({
    path: "/free-otp-generator",
    titleEn: "Free OTP generator",
    titleZh: "免费 OTP 生成器",
    titles: { "zh-tw": "免費 OTP 產生器", es: "Generador OTP gratuito", ja: "無料 OTP ジェネレーター", de: "Kostenloser OTP-Generator", fr: "Générateur OTP gratuit", ko: "무료 OTP 생성기" },
    descEn: "A free, ad-free OTP generator that runs entirely in the browser.",
    descZh: "完全在浏览器中运行的免费、无广告 OTP 生成器。",
    h1En: "Free as in no account and no advertising",
    h1Zh: "免费意味着没有账号也没有广告",
    introEn: "There is no paid tier because there is no server-side feature to sell. The generator is the static site.",
    introZh: "没有付费档，因为没有可卖的服务端功能。生成器就是这个静态站点。",
    bodyEn: "<p>OTP here means TOTP, not SMS one-time passwords and not email magic links. Those are delivered, not computed from a setup key you hold.</p>",
    bodyZh: "<p>这里的 OTP 指 TOTP，不是短信一次性密码，也不是邮箱魔术链接。那些是投递的，不是由你持有的设置密钥计算出来的。</p>",
    q1e: "Hidden telemetry?", a1e: "Not in this bundle. Your host's access logs are separate.",
    q2e: "License?", a2e: "See the repository when you publish it. The implementation is original.",
    q3e: "Why not an extension?", a3e: "A page with no extra permissions is easier to audit.",
    q1z: "有隐藏遥测吗？", a1z: "本打包没有。托管方的访问日志是另一回事。",
    q2z: "许可证？", a2z: "发布仓库时再说明。实现是原创的。",
    q3z: "为什么不是扩展？", a3z: "没有额外权限的页面更容易审计。",
  }),
  tool({
    path: "/authenticator-code-generator",
    titleEn: "Authenticator code generator",
    titleZh: "验证器验证码生成器",
    titles: { "zh-tw": "驗證器驗證碼產生器", es: "Generador de códigos de autenticador", ja: "認証コード生成", de: "Authenticator-Codegenerator", fr: "Générateur de codes authenticator", ko: "인증 코드 생성기" },
    descEn: "Generate authenticator-style codes from keys you already hold.",
    descZh: "用你已持有的密钥生成验证器风格的验证码。",
    h1En: "Authenticator codes without another home-screen icon",
    h1Zh: "不必再占一个主屏图标的验证器验证码",
    introEn: "Useful on a locked-down work laptop that cannot install the usual authenticator, as long as policy allows a browser calculator.",
    introZh: "在不能安装常规验证器的锁定工作笔记本上很有用，前提是政策允许使用浏览器计算器。",
    bodyEn: "<p>Still keep a durable copy of the setup key offline. This page will not remind you tomorrow.</p>",
    bodyZh: "<p>仍要把设置密钥的耐久副本放在离线处。本页明天不会提醒你。</p>",
    q1e: "Group policies blocking clipboard?", a1e: "Type the key. Paste requires clipboard permission.",
    q2e: "Shared kiosk?", a2e: "Do not enter production keys on a kiosk.",
    q3e: "Print the code?", a3e: "It expires. Print backup codes from the issuer instead.",
    q1z: "组策略禁止剪贴板？", a1z: "手动输入密钥。粘贴需要剪贴板权限。",
    q2z: "共用自助终端？", a2z: "不要在自助终端输入生产密钥。",
    q3z: "把验证码打印出来？", a3z: "它会过期。请改为打印发行方的备用码。",
  }),
  tool({
    path: "/google-authenticator-online",
    titleEn: "Google Authenticator online",
    titleZh: "在线 Google Authenticator",
    titles: { "zh-tw": "線上 Google Authenticator", es: "Google Authenticator en línea", ja: "オンライン版 Google Authenticator", de: "Google Authenticator online", fr: "Google Authenticator en ligne", ko: "온라인 Google Authenticator" },
    descEn: "An online calculator with Google Authenticator default TOTP parameters.",
    descZh: "采用 Google Authenticator 默认 TOTP 参数的在线计算器。",
    h1En: "Online companion, not a rebranded Google product",
    h1Zh: "在线伴侣，不是换皮的 Google 产品",
    introEn: "Searchers looking for Google Authenticator online usually need SHA-1 six-digit codes in a browser. That is what this route provides, without Google sign-in.",
    introZh: "搜索“在线 Google Authenticator”的人通常需要浏览器里的 SHA-1 六位验证码。本路由就是这个，而且不用 Google 登录。",
    bodyEn: "<p>Transfer accounts with Google's official export. This page will not read a Google account or cloud backup.</p>",
    bodyZh: "<p>请用 Google 官方导出转移账户。本页不会读取 Google 账号或云备份。</p>",
    q1e: "Transfer QR from Google Authenticator?", a1e: "Those bulk migration QRs are a different format and are not decoded here.",
    q2e: "Wear OS support?", a2e: "Not applicable. Use the official app on a watch.",
    q3e: "Same codes as the phone?", a3e: "Yes, when key, time, digits, period, and algorithm match.",
    q1z: "Google Authenticator 的转移二维码？", a1z: "那些批量迁移二维码是另一种格式，这里不解。",
    q2z: "Wear OS？", a2z: "不适用。手表请用官方应用。",
    q3z: "和手机上的码一样吗？", a3z: "当密钥、时间、位数、周期和算法一致时，一样。",
  }),
  tool({
    path: "/two-factor-authentication-code-generator",
    titleEn: "Two-factor authentication code generator",
    titleZh: "双因素认证验证码生成器",
    titles: { "zh-tw": "雙因素認證驗證碼產生器", es: "Generador de códigos de autenticación en dos factores", ja: "二要素認証コード生成", de: "Zwei-Faktor-Codegenerator", fr: "Générateur de codes d’authentification à deux facteurs", ko: "이중 인증 코드 생성기" },
    descEn: "Two-factor authentication codes from a TOTP setup key.",
    descZh: "由 TOTP 设置密钥得到双因素认证验证码。",
    h1En: "Two-factor codes are short; the key is long",
    h1Zh: "双因素验证码很短，密钥很长",
    introEn: "The long Base32 string is the second factor material. The short number is a perishable proof. Only the short number belongs in a login form.",
    introZh: "长的 Base32 字符串才是第二因素材料。短数字是易过期的证明。只有短数字属于登录表单。",
    bodyEn: "<p>Pairing a password with TOTP raises the bar versus password-only, as NIST SP 800-63B discusses. It is still phishable if you type the code into a fake site.</p>",
    bodyZh: "<p>如 NIST SP 800-63B 所述，密码加 TOTP 比仅密码门槛更高。若你把验证码打进假网站，它仍可被钓鱼。</p>",
    q1e: "Passkeys instead?", a1e: "Use them when offered. This generator does not create passkeys.",
    q2e: "Both passkey and TOTP?", a2e: "Good idea if the issuer allows both.",
    q3e: "Recovery still needed?", a3e: "Yes. Keep backup codes even if this page works today.",
    q1z: "改用通行密钥？", a1z: "有就用。本生成器不创建通行密钥。",
    q2z: "通行密钥和 TOTP 一起？", a2z: "如果发行方允许，这是好主意。",
    q3z: "仍需要恢复手段吗？", a3z: "需要。即使本页今天能用，也要保留备用码。",
  }),
  tool({
    path: "/online-one-time-password-generator",
    titleEn: "Online one-time password generator",
    titleZh: "在线一次性密码生成器",
    titles: { "zh-tw": "線上一次性密碼產生器", es: "Generador de contraseñas de un solo uso en línea", ja: "オンラインワンタイムパスワード生成", de: "Online-Einmalpasswort-Generator", fr: "Générateur de mot de passe à usage unique en ligne", ko: "온라인 일회용 비밀번호 생성기" },
    descEn: "Online one-time passwords computed locally as TOTP.",
    descZh: "在本地按 TOTP 计算的在线一次性密码。",
    h1En: "One-time means the window, not a random draw",
    h1Zh: "一次性指的是时间窗，不是随机抽取",
    introEn: "These passwords are deterministic for a given second. Anyone with the key and a good clock gets the same digits. Random.org-style draws would not log you in.",
    introZh: "这些密码在给定秒数上是确定的。持有密钥且时钟正确的人会得到同一串数字。随机网站式的抽取无法登录。",
    bodyEn: "<p>That is why leaking the setup key is equivalent to leaking future OTPs. This UI refuses to persist it.</p>",
    bodyZh: "<p>所以泄露设置密钥等于泄露未来的 OTP。本界面拒绝持久化它。</p>",
    q1e: "Can I email myself the key?", a1e: "Email is another copy. Prefer a password manager or paper.",
    q2e: "Screenshot the dashes?", a2e: "Wait until real digits appear.",
    q3e: "Period end?", a3e: "The ring hits 0 then rolls to a new code on the next tick.",
    q1z: "能把密钥发到自己邮箱吗？", a1z: "邮箱又是一份副本。更推荐密码管理器或纸张。",
    q2z: "把短横线截图？", a2z: "等到真正的数字出现。",
    q3z: "周期结束？", a3z: "圆环到 0 后，下一次滴答会换成新码。",
  }),
  tool({
    path: "/otp-code-generator",
    titleEn: "OTP code generator",
    titleZh: "OTP 验证码生成器",
    titles: { "zh-tw": "OTP 驗證碼產生器", es: "Generador de códigos OTP", ja: "OTP コード生成", de: "OTP-Codegenerator", fr: "Générateur de codes OTP", ko: "OTP 코드 생성기" },
    descEn: "Compact OTP code generator for TOTP setup keys.",
    descZh: "面向 TOTP 设置密钥的紧凑 OTP 验证码生成器。",
    h1En: "OTP codes, no extra chrome beyond the essentials",
    h1Zh: "OTP 验证码，除必要元素外没有多余装饰",
    introEn: "If you already live in the TOTP jargon, this route is a short alias to the same generator widget used across the site.",
    introZh: "如果你已经熟悉 TOTP 术语，这条路由就是全站同一个生成器组件的短别名。",
    bodyEn: "<p>JSON-LD FAQPage is attached so search engines can surface the three questions below. Human readers still get the unique intro on this URL.</p>",
    bodyZh: "<p>附带 JSON-LD FAQPage，方便搜索引擎展示下面三个问题。人类读者仍会在此 URL 看到独特的导语。</p>",
    q1e: "Is this a different algorithm?", a1e: "No. Same RFC 6238 implementation as every tool page.",
    q2e: "Why so many URLs?", a2e: "People search different phrases. Each page keeps a unique H1 and FAQ.",
    q3e: "Sitemap include?", a3e: "Yes. /otp-code-generator is in the tools sitemap.",
    q1z: "这是另一种算法吗？", a1z: "不是。与每个工具页相同的 RFC 6238 实现。",
    q2z: "为什么有这么多 URL？", a2z: "人们用不同短语搜索。每个页面保持独特的 H1 和 FAQ。",
    q3z: "会进入站点地图吗？", a3z: "会。/otp-code-generator 在工具站点地图中。",
  }),
];
