import { tool } from "./tool-helper";
import { SHA1_6 } from "./routes-types";

export const TOOL_ROUTES_A = [
  tool({
    path: "/online-totp-generator",
    titleEn: "Online TOTP generator",
    titleZh: "在线 TOTP 生成器",
    titles: { "zh-tw": "線上 TOTP 產生器", es: "Generador TOTP en línea", ja: "オンライン TOTP ジェネレーター", de: "Online-TOTP-Generator", fr: "Générateur TOTP en ligne", ko: "온라인 TOTP 생성기", pt: "Gerador TOTP online", ru: "Онлайн-генератор TOTP", hi: "ऑनलाइन TOTP जनरेटर", ar: "مولّد TOTP عبر المتصفح", it: "Generatore TOTP online", tr: "Çevrimiçi TOTP üreteci", vi: "Bộ tạo TOTP trực tuyến", id: "Generator TOTP daring", th: "ตัวสร้าง TOTP ออนไลน์", nl: "Online TOTP-generator", pl: "Generator TOTP online", uk: "Онлайн-генератор TOTP", bn: "অনলাইন TOTP জেনারেটর" },
    descEn: "Browser TOTP generator that never posts the setup key.",
    descZh: "从不提交设置密钥的浏览器 TOTP 生成器。",
    h1En: "Online only in the sense that it is a web page",
    h1Zh: "所谓在线，只是因为它是一个网页",
    introEn: "This online TOTP generator is a static page. After load, HMAC-SHA1/256/512 runs in the tab. It is online as a distribution method, not as a web service that receives keys.",
    introZh: "这个在线 TOTP 生成器是静态页。加载后 HMAC-SHA1/256/512 在标签页内运行。它的“在线”只是分发方式，不是接收密钥的网络服务。",
    bodyEn: "<p>Paste a Base32 key or otpauth URI. Add extra generator cards if you are rotating several accounts on a borrowed computer that you will close afterwards.</p>",
    bodyZh: "<p>粘贴 Base32 密钥或 otpauth 链接。如果在用完即关的借用电脑上轮换多个账户，可以添加多张生成器卡片。</p>",
    q1e: "Is the code sent anywhere?", a1e: "No. The digits are rendered from Web Crypto output in this document.",
    q2e: "Which defaults?", a2e: "SHA-1, 6 digits, 30 seconds unless the URI says otherwise.",
    q3e: "Can I host it myself?", a3e: "Yes. Build with Vite and publish the dist folder.",
    q1z: "验证码会发到别处吗？", a1z: "不会。数字来自本文档中 Web Crypto 的输出。",
    q2z: "默认参数是什么？", a2z: "除非 URI 另有说明，否则是 SHA-1、6 位、30 秒。",
    q3z: "可以自己托管吗？", a3z: "可以。用 Vite 构建并发布 dist 目录。",
    defaults: SHA1_6,
  }),
  tool({
    path: "/2fa-generator",
    titleEn: "2FA generator",
    titleZh: "2FA 生成器",
    titles: { "zh-tw": "2FA 產生器", es: "Generador 2FA", ja: "2FA ジェネレーター", de: "2FA-Generator", fr: "Générateur 2FA", ko: "2FA 생성기", pt: "Gerador 2FA", ru: "Генератор 2FA", ar: "مولّد 2FA", hi: "2FA जनरेटर", it: "Generatore 2FA", tr: "2FA üreteci", vi: "Bộ tạo 2FA", id: "Generator 2FA", th: "ตัวสร้าง 2FA", nl: "2FA-generator", pl: "Generator 2FA", uk: "Генератор 2FA", bn: "2FA জেনারেটর" },
    descEn: "Local two-factor code generator for TOTP setup keys.",
    descZh: "面向 TOTP 设置密钥的本地双因素验证码生成器。",
    h1En: "A 2FA generator is just TOTP with a friendlier name",
    h1Zh: "所谓 2FA 生成器，不过是更好记的 TOTP",
    introEn: "People search for a 2FA generator when they need the six-digit code that sits next to a password. Under the hood that is RFC 6238 TOTP, not a proprietary ChatGPT or Google algorithm.",
    introZh: "人们找 2FA 生成器，是因为需要密码旁边那串六位数字。底层是 RFC 6238 TOTP，不是 ChatGPT 或 Google 的专有算法。",
    bodyEn: "<p>Use this page as a spare calculator. Enrollment of new accounts should still happen in an authenticator you back up, so you are not dependent on a browser profile.</p>",
    bodyZh: "<p>把本页当备用计算器。新账户仍应在你会备份的验证器里登记，这样才不会绑死在某个浏览器配置上。</p>",
    q1e: "Does this enroll my account?", a1e: "No. It only computes codes from a key you already have.",
    q2e: "SMS 2FA too?", a2e: "No. SMS codes are sent by the issuer; they are not HMAC of a setup key.",
    q3e: "Multiple accounts?", a3e: "Use + Add generator. Each card is independent and still not persisted.",
    q1z: "这会登记我的账户吗？", a1z: "不会。它只根据你已有的密钥计算验证码。",
    q2z: "也支持短信 2FA 吗？", a2z: "不。短信验证码由发行方发送，不是设置密钥的 HMAC。",
    q3z: "多个账户怎么办？", a3z: "使用“添加生成器”。每张卡片独立，并且仍然不会落盘。",
  }),
  tool({
    path: "/totp-generator",
    titleEn: "TOTP generator",
    titleZh: "TOTP 生成器",
    titles: { "zh-tw": "TOTP 產生器", es: "Generador TOTP", ja: "TOTP ジェネレーター", de: "TOTP-Generator", fr: "Générateur TOTP", ko: "TOTP 생성기", pt: "Gerador TOTP", ru: "Генератор TOTP", ar: "مولّد TOTP", hi: "TOTP जनरेटर", it: "Generatore TOTP", tr: "TOTP üreteci", vi: "Bộ tạo TOTP", id: "Generator TOTP", th: "ตัวสร้าง TOTP", nl: "TOTP-generator", pl: "Generator TOTP", uk: "Генератор TOTP", bn: "TOTP জেনারেটর" },
    descEn: "Straightforward TOTP generator with digits, period, and algorithm controls.",
    descZh: "可调节位数、周期和算法的直接 TOTP 生成器。",
    h1En: "The default TOTP generator on this site",
    h1Zh: "本站默认的 TOTP 生成器",
    introEn: "Start here if you already know you need TOTP. Defaults are SHA-1, 6 digits, and a 30 second period, matching the majority of consumer enrollments.",
    introZh: "如果你已经知道需要 TOTP，从这里开始。默认 SHA-1、6 位、30 秒，与大多数消费级登记一致。",
    bodyEn: "<p>Open TOTP options to switch to 8 digits or SHA-256/512. The countdown ring uses radius 62 and ticks once per second.</p>",
    bodyZh: "<p>打开 TOTP 选项可切换到 8 位或 SHA-256/512。倒计时环半径为 62，每秒刷新一次。</p>",
    q1e: "What key formats work?", a1e: "Base32 (A–Z2–7) and otpauth://totp/ URIs.",
    q2e: "How do I copy the code?", a2e: "Click the large digits or focus them and press Enter.",
    q3e: "Is SHA-1 unsafe here?", a3e: "TOTP still commonly uses HMAC-SHA1 as specified. Prefer SHA-256 when the issuer offers it.",
    q1z: "支持哪些密钥格式？", a1z: "Base32（A–Z2–7）以及 otpauth://totp/ 链接。",
    q2z: "如何复制验证码？", a2z: "点击大号数字，或聚焦后按 Enter。",
    q3z: "这里用 SHA-1 不安全吗？", a3z: "TOTP 仍普遍按规范使用 HMAC-SHA1。若发行方提供 SHA-256，请优先使用。",
  }),
];
