import { tool } from "./tool-helper";
import { SHA1_8, SHA256_6, SHA512_6 } from "./routes-types";

export const TOOL_ROUTES_F = [
  tool({
    path: "/otpauth-totp-generator",
    titleEn: "otpauth TOTP generator",
    titleZh: "otpauth TOTP 生成器",
    titles: { "zh-tw": "otpauth TOTP 產生器", es: "Generador TOTP otpauth", ja: "otpauth TOTP ジェネレーター", de: "otpauth-TOTP-Generator", fr: "Générateur TOTP otpauth", ko: "otpauth TOTP 생성기" },
    descEn: "Paste an otpauth://totp/ URI and generate codes with its parameters.",
    descZh: "粘贴 otpauth://totp/ 链接，并按其参数生成验证码。",
    h1En: "The URI already carries algorithm, digits, and period",
    h1Zh: "链接里已经带有算法、位数和周期",
    introEn: "otpauth://totp/Issuer:account?secret=...&algorithm=SHA256&digits=8&period=30 is enough. The generator parses query fields and the label.",
    introZh: "otpauth://totp/Issuer:account?secret=...&algorithm=SHA256&digits=8&period=30 就够了。生成器会解析查询字段和标签。",
    bodyEn: "<p>Only the totp type is accepted. Missing secret is an error. Algorithm spellings SHA1, SHA-1, SHA256, SHA-512 all map to Web Crypto hash names.</p>",
    bodyZh: "<p>只接受 totp 类型。缺少 secret 会报错。SHA1、SHA-1、SHA256、SHA-512 等写法都会映射到 Web Crypto 的哈希名。</p>",
    q1e: "Issuer vs label?", a1e: "Name prefers the issuer query, then the path label.",
    q2e: "Percent-encoding?", a2e: "Decoded with the URL parser.",
    q3e: "hotp in the URI?", a3e: "Rejected with a parse error so you do not get a plausible but wrong code.",
    q1z: "发行方和标签？", a1z: "名称优先用 issuer 查询参数，其次是路径标签。",
    q2z: "百分号编码？", a2z: "由 URL 解析器解码。",
    q3z: "URI 里是 hotp？", a3z: "解析会失败，以免你得到看起来合理却错误的码。",
  }),
  tool({
    path: "/totp-parameters",
    titleEn: "TOTP parameters",
    titleZh: "TOTP 参数",
    titles: { "zh-tw": "TOTP 參數", es: "Parámetros TOTP", ja: "TOTP パラメータ", de: "TOTP-Parameter", fr: "Paramètres TOTP", ko: "TOTP 매개변수" },
    descEn: "Tune digits, period, and HMAC algorithm for a TOTP key.",
    descZh: "为 TOTP 密钥调节位数、周期和 HMAC 算法。",
    h1En: "Three knobs: digits, period, algorithm",
    h1Zh: "三个旋钮：位数、周期、算法",
    introEn: "Consumer defaults hide these knobs. Enterprise IdPs sometimes do not. This page surfaces them in TOTP options on every card.",
    introZh: "消费级默认会藏起这些旋钮。企业 IdP 有时不会。本页在每张卡片的 TOTP 选项里把它们摊开。",
    bodyEn: "<p>Digits are 6 or 8. Period is 10–120 seconds in steps of 5, shown with an s suffix. Algorithms are SHA-1, SHA-256, and SHA-512 via crypto.subtle HMAC.</p>",
    bodyZh: "<p>位数为 6 或 8。周期为 10–120 秒、步进 5，并带 s 后缀。算法为通过 crypto.subtle HMAC 的 SHA-1、SHA-256 和 SHA-512。</p>",
    q1e: "Why not 7 digits?", a1e: "Issuers in the wild use 6 or 8. Supporting 7 would invite mismatches.",
    q2e: "Period 0?", a2e: "Rejected by the input min of 10.",
    q3e: "SHA-3?", a3e: "Not in RFC 6238. Not offered.",
    q1z: "为什么没有 7 位？", a1z: "现实中的发行方用 6 或 8。支持 7 位更容易对不上。",
    q2z: "周期 0？", a2z: "输入最小值 10，会被拒绝。",
    q3z: "SHA-3？", a3z: "RFC 6238 没有。不提供。",
  }),
  tool({
    path: "/8-digit-totp-generator",
    titleEn: "8-digit TOTP generator",
    titleZh: "8 位 TOTP 生成器",
    titles: { "zh-tw": "8 位 TOTP 產生器", es: "Generador TOTP de 8 dígitos", ja: "8 桁 TOTP ジェネレーター", de: "8-stelliger TOTP-Generator", fr: "Générateur TOTP 8 chiffres", ko: "8자리 TOTP 생성기" },
    descEn: "Defaults to SHA-1, 8 digits, 30 seconds for RFC-style codes.",
    descZh: "默认 SHA-1、8 位、30 秒，用于 RFC 风格验证码。",
    h1En: "Eight digits, SHA-1, thirty seconds",
    h1Zh: "八位数字、SHA-1、三十秒",
    introEn: "This route starts with 8-digit SHA-1 TOTP so RFC 6238 Appendix B demos and some banks do not require hunting through options first.",
    introZh: "此路由默认 8 位 SHA-1 TOTP，这样 RFC 6238 附录 B 演示和部分银行不必先翻选项。",
    bodyEn: "<p>You can still drop back to 6 digits. The RFC vectors JSON in /rfc6238-test-vectors.json is 8-digit on purpose.</p>",
    bodyZh: "<p>仍可改回 6 位。/rfc6238-test-vectors.json 里的 RFC 向量故意使用 8 位。</p>",
    q1e: "Are 8-digit codes more secure?", a1e: "They expand the search space slightly. The key length and storage hygiene matter more.",
    q2e: "Will Google Authenticator show 8 digits?", a2e: "Only if the otpauth URI asked for digits=8 and the app honors it.",
    q3e: "Zero pad?", a3e: "Yes. 07081804 stays eight characters.",
    q1z: "8 位更安全吗？", a1z: "搜索空间略大。密钥长度和保管习惯更重要。",
    q2z: "Google Authenticator 会显示 8 位吗？", a2z: "只有 otpauth 要求 digits=8 且应用遵守时才会。",
    q3z: "补零吗？", a3z: "会。07081804 保持八个字符。",
    defaults: SHA1_8,
  }),
  tool({
    path: "/sha256-totp-generator",
    titleEn: "SHA-256 TOTP generator",
    titleZh: "SHA-256 TOTP 生成器",
    titles: { "zh-tw": "SHA-256 TOTP 產生器", es: "Generador TOTP SHA-256", ja: "SHA-256 TOTP ジェネレーター", de: "SHA-256-TOTP-Generator", fr: "Générateur TOTP SHA-256", ko: "SHA-256 TOTP 생성기" },
    descEn: "HMAC-SHA-256 TOTP with 6 digits and a 30 second period by default.",
    descZh: "默认 6 位、30 秒的 HMAC-SHA-256 TOTP。",
    h1En: "SHA-256 TOTP for issuers that moved past SHA-1",
    h1Zh: "面向已离开 SHA-1 的发行方的 SHA-256 TOTP",
    introEn: "This page defaults to HMAC-SHA-256, 6 digits, 30 seconds. Many phone apps still assume SHA-1; confirm the otpauth algorithm field.",
    introZh: "本页默认 HMAC-SHA-256、6 位、30 秒。许多手机应用仍假设 SHA-1；请确认 otpauth 的 algorithm 字段。",
    bodyEn: "<p>RFC 6238 Appendix B includes SHA-256 vectors using a 32-byte ASCII key. Tests inject unix time rather than reading Date.now.</p>",
    bodyZh: "<p>RFC 6238 附录 B 包含使用 32 字节 ASCII 密钥的 SHA-256 向量。测试注入 unix 时间，而不读取 Date.now。</p>",
    q1e: "Is SHA-256 supported in Web Crypto?", a1e: "Yes. crypto.subtle HMAC with hash SHA-256 is used.",
    q2e: "Same key as SHA-1?", a2e: "Only if the issuer used the same bytes. Do not mix algorithms for one enrollment.",
    q3e: "Default digits?", a3e: "6 on this route. Switch to 8 if needed.",
    q1z: "Web Crypto 支持 SHA-256 吗？", a1z: "支持。使用 hash 为 SHA-256 的 crypto.subtle HMAC。",
    q2z: "能和 SHA-1 用同一把密钥吗？", a2z: "只有发行方使用相同字节才行。一次登记不要混用算法。",
    q3z: "默认位数？", a3z: "此路由为 6。需要可改为 8。",
    defaults: SHA256_6,
  }),
  tool({
    path: "/sha512-totp-generator",
    titleEn: "SHA-512 TOTP generator",
    titleZh: "SHA-512 TOTP 生成器",
    titles: { "zh-tw": "SHA-512 TOTP 產生器", es: "Generador TOTP SHA-512", ja: "SHA-512 TOTP ジェネレーター", de: "SHA-512-TOTP-Generator", fr: "Générateur TOTP SHA-512", ko: "SHA-512 TOTP 생성기" },
    descEn: "HMAC-SHA-512 TOTP with 6 digits and a 30 second period by default.",
    descZh: "默认 6 位、30 秒的 HMAC-SHA-512 TOTP。",
    h1En: "SHA-512 TOTP when the URI says SHA512",
    h1Zh: "当 URI 写明 SHA512 时使用 SHA-512 TOTP",
    introEn: "Defaults: HMAC-SHA-512, 6 digits, 30 seconds. The RFC demo key is 64 ASCII bytes; the UI also accepts its Base32 spelling.",
    introZh: "默认：HMAC-SHA-512、6 位、30 秒。RFC 演示密钥是 64 字节 ASCII；界面也接受它的 Base32 写法。",
    bodyEn: "<p>Truncation still uses the HOTP dynamic offset into the HMAC output. Longer hashes do not mean longer codes unless you raise digits.</p>",
    bodyZh: "<p>截断仍使用 HOTP 动态偏移取 HMAC 输出。哈希更长并不等于验证码更长，除非你提高位数。</p>",
    q1e: "Do common apps support SHA-512?", a1e: "Support is uneven. Prefer this route only when the issuer specified SHA-512.",
    q2e: "Performance?", a2e: "Negligible in a browser for a single HMAC per second.",
    q3e: "RFC vectors?", a3e: "Shipped in public/rfc6238-test-vectors.json and asserted in vitest.",
    q1z: "常见应用支持 SHA-512 吗？", a1z: "支持情况不一。只在发行方指定 SHA-512 时走此路由。",
    q2z: "性能？", a2z: "浏览器里每秒一次 HMAC 可忽略。",
    q3z: "RFC 向量？", a3z: "放在 public/rfc6238-test-vectors.json 中，并在 vitest 里断言。",
    defaults: SHA512_6,
  }),
];
