import { expandPage } from "./page-factory";
import { SHA1_6 } from "./routes-types";

export const HOME_ROUTE = expandPage({
  path: "/",
  kind: "home",
  showGenerator: true,
  showMatrix: true,
  defaults: SHA1_6,
  titleEn: "Local TOTP — private 2FA codes in your browser",
  titleZh: "本地 TOTP — 浏览器内的私密 2FA 验证码",
  titles: {
    "zh-tw": "本機 TOTP — 瀏覽器內的私密 2FA 驗證碼",
    es: "TOTP local — códigos 2FA privados en el navegador",
    hi: "स्थानीय TOTP — ब्राउज़र में निजी 2FA कोड",
    ar: "TOTP محلي — رموز 2FA خاصة في المتصفح",
    bn: "স্থানীয় TOTP — ব্রাউজারে ব্যক্তিগত 2FA কোড",
    pt: "TOTP local — códigos 2FA privados no navegador",
    ru: "Локальный TOTP — приватные коды 2FA в браузере",
    ja: "ローカル TOTP — ブラウザで完結する 2FA コード",
    de: "Lokales TOTP — private 2FA-Codes im Browser",
    fr: "TOTP local — codes 2FA privés dans le navigateur",
    ko: "로컬 TOTP — 브라우저에서 끝나는 비공개 2FA 코드",
    it: "TOTP locale — codici 2FA privati nel browser",
    tr: "Yerel TOTP — tarayıcıda özel 2FA kodları",
    vi: "TOTP cục bộ — mã 2FA riêng trong trình duyệt",
    id: "TOTP lokal — kode 2FA privat di browser",
    th: "TOTP ในเครื่อง — รหัส 2FA ส่วนตัวในเบราว์เซอร์",
    nl: "Lokale TOTP — privé 2FA-codes in de browser",
    pl: "Lokalny TOTP — prywatne kody 2FA w przeglądarce",
    uk: "Локальний TOTP — приватні коди 2FA в браузері",
  },
  descEn: "Generate RFC 6238 TOTP codes locally with Web Crypto. Secrets never leave this device.",
  descZh: "用 Web Crypto 在本地生成 RFC 6238 TOTP 验证码。密钥不会离开这台设备。",
  h1En: "A TOTP workbench that keeps secrets on this device",
  h1Zh: "密钥留在本机的 TOTP 工作台",
  introEn: "This static site turns a Base32 setup key or an otpauth URI into the same rotating code an authenticator app would show. HMAC runs in Web Crypto in this browser. Setup keys can stay in this browser’s localStorage (totpLocalVault) until you delete them; they never go to a server.",
  introZh: "这个静态站点把 Base32 设置密钥或 otpauth 链接转成验证器应用会显示的同一组滚动验证码。HMAC 在本浏览器的 Web Crypto 中完成。设置密钥可以留在本机 localStorage（totpLocalVault）直到你删除；它们不会上传服务器。",
  bodyEn: "<p>Use the generator when a phone app is inconvenient, when you need to check a setup key before enrolling a device, or when you want SHA-256 / SHA-512 / 8-digit variants that some apps hide. Prefer putting secrets in the URL fragment (<code>#secret=</code>) so they are not sent to a host in a request line.</p><p>Nothing here impersonates a vendor authenticator. Official apps remain the right place to enroll ChatGPT, Google, Microsoft, and other accounts. This page is a local calculator plus documentation of the TOTP parameters those apps implement.</p>",
  bodyZh: "<p>当你不方便打开手机应用、想在登记设备前核对设置密钥，或需要部分应用未暴露的 SHA-256 / SHA-512 / 8 位变体时，可以使用这里的生成器。密钥请优先放在 URL 片段（<code>#secret=</code>）中，这样不会出现在请求行里发给主机。</p><p>本站不冒充任何厂商验证器。登记 ChatGPT、Google、Microsoft 等账户仍应使用官方应用。本页是本地计算器，并说明这些应用实现的 TOTP 参数。</p>",
  faqEn: [
    ["Does this site upload my 2FA secret?", "No. Encoding, HMAC, and the six- or eight-digit display all happen in JavaScript in this tab. There is no account API."],
    ["Why is localStorage mentioned at all?", "Language choice is remembered as totpPreferredLanguage. Setup keys you keep as history are stored only as totpLocalVault in this browser. Nothing is sent to a server."],
    ["Can I bookmark a secret?", "You can, using a fragment such as #secret=YOURBASE32, but anyone with that bookmark can mint codes. Treat it like a password."],
  ],
  faqZh: [
    ["这个站点会上传我的 2FA 密钥吗？", "不会。编码、HMAC 以及 6 位或 8 位显示都在本标签页的 JavaScript 中完成。没有账户接口。"],
    ["为什么还提到 localStorage？", "语言选择记在 totpPreferredLanguage。你保留的设置密钥只作为 totpLocalVault 存在本浏览器，不会上传服务器。"],
    ["我可以收藏带密钥的链接吗？", "可以，例如使用片段 #secret=YOURBASE32，但拿到该收藏的人也能生成验证码。请把它当密码对待。"],
  ],
});
