import { expandPage, type CompactPage } from "./page-factory";

const guides: CompactPage[] = [
  {
    path: "/2fa-vs-mfa",
    kind: "guide",
    titleEn: "2FA vs MFA",
    titleZh: "2FA 与 MFA",
    titles: { "zh-tw": "2FA 與 MFA", es: "2FA frente a MFA", hi: "2FA बनाम MFA", ar: "2FA مقابل MFA", bn: "2FA বনাম MFA", pt: "2FA vs MFA", ru: "2FA и MFA", ja: "2FA と MFA", de: "2FA vs. MFA", fr: "2FA vs MFA", ko: "2FA와 MFA", it: "2FA e MFA", tr: "2FA ve MFA", vi: "2FA và MFA", id: "2FA vs MFA", th: "2FA กับ MFA", nl: "2FA vs MFA", pl: "2FA a MFA", uk: "2FA і MFA" },
    descEn: "How two-factor authentication relates to multi-factor authentication.",
    descZh: "双因素认证与多因素认证的关系。",
    h1En: "2FA is MFA with exactly two factors",
    h1Zh: "2FA 就是恰好两个因素的 MFA",
    introEn: "Multi-factor authentication means proving more than one category of credential: something you know, have, or are. Two-factor authentication is the common case of pairing a password with a possession factor such as TOTP.",
    introZh: "多因素认证意味着证明不止一类凭据：你知道的、拥有的或你本身。双因素认证是常见情形，把密码与 TOTP 这类持有因素配对。",
    bodyEn: "<p>A TOTP code is a possession factor only if the setup key stays on a device you control. Copying the same key into a browser generator and a phone app does not create a second factor; it clones the first possession factor.</p>",
    bodyZh: "<p>只有当设置密钥留在你控制的设备上时，TOTP 才算持有因素。把同一密钥同时放进浏览器生成器和手机应用，并不会增加一个因素，只是克隆了原来的持有因素。</p>",
    faqEn: [["Does MFA require a hardware key?", "No. TOTP, push approval, and passkeys can all participate. Hardware keys are one strong option."], ["Is email a second factor?", "Email is often still a knowledge-adjacent channel. Treat it as weaker than TOTP or a security key."]],
    faqZh: [["MFA 必须用硬件密钥吗？", "不必。TOTP、推送确认和通行密钥都可以参与。硬件密钥是其中一种更强的选项。"], ["邮箱算第二因素吗？", "邮箱往往仍接近“你知道的”通道。它通常弱于 TOTP 或安全密钥。"]],
  },
  {
    path: "/totp-vs-hotp",
    kind: "guide",
    titleEn: "TOTP vs HOTP",
    titleZh: "TOTP 与 HOTP",
    titles: { "zh-tw": "TOTP 與 HOTP", es: "TOTP frente a HOTP", ja: "TOTP と HOTP", de: "TOTP vs. HOTP", fr: "TOTP vs HOTP", ko: "TOTP와 HOTP", pt: "TOTP vs HOTP", ru: "TOTP и HOTP" },
    descEn: "The difference between time-based and counter-based one-time passwords.",
    descZh: "基于时间与基于计数器的一次性密码有何不同。",
    h1En: "HOTP counts events; TOTP counts seconds",
    h1Zh: "HOTP 计次数，TOTP 计秒数",
    introEn: "HOTP (RFC 4226) feeds an incrementing counter into HMAC. TOTP (RFC 6238) replaces that counter with a time step. Authenticator apps almost always speak TOTP for account logins.",
    introZh: "HOTP（RFC 4226）把递增计数器送入 HMAC。TOTP（RFC 6238）用时间步替代该计数器。账户登录用的验证器应用几乎都是 TOTP。",
    bodyEn: "<p>This generator implements TOTP only. If a system still uses HOTP, a time-based code will not match. Look at the otpauth URI: the host should read totp, not hotp.</p>",
    bodyZh: "<p>本生成器只实现 TOTP。如果系统仍用 HOTP，按时间算出的码对不上。请看 otpauth 链接：主机部分应是 totp 而不是 hotp。</p>",
    faqEn: [["Can I convert HOTP to TOTP?", "Not by changing the code length. The moving factor is different; the issuer must enroll a TOTP key."], ["Why do codes expire?", "Because the time step moved. Default period is 30 seconds in the RFC examples."]],
    faqZh: [["HOTP 能转成 TOTP 吗？", "改位数不行。移动因子不同，必须由发行方重新登记 TOTP 密钥。"], ["验证码为什么会过期？", "因为时间步前进了。RFC 示例里默认周期是 30 秒。"]],
  },
  {
    path: "/2fa-setup-key-guide",
    kind: "guide",
    titleEn: "2FA setup key guide",
    titleZh: "2FA 设置密钥指南",
    titles: { "zh-tw": "2FA 設定金鑰指南", es: "Guía de clave de configuración 2FA", ja: "2FA セットアップキー案内", de: "Leitfaden zum 2FA-Setup-Schlüssel", fr: "Guide de la clé 2FA", ko: "2FA 설정 키 안내" },
    descEn: "How to read a Base32 setup key and keep it offline.",
    descZh: "如何阅读 Base32 设置密钥并离线保管。",
    h1En: "The setup key is the whole authenticator",
    h1Zh: "设置密钥就是整个验证器",
    introEn: "When a site shows a QR code, it is wrapping a Base32 secret plus optional issuer, digits, period, and algorithm. Anyone who copies that key can mint the same codes.",
    introZh: "网站展示二维码时，包装的是 Base32 密钥以及可选的发行方、位数、周期和算法。谁复制了这把密钥，谁就能算出同一组验证码。",
    bodyEn: "<p>Write the key on paper or store it in a password manager that you already trust. Do not paste it into random web forms. This local generator keeps it in RAM for the tab only.</p>",
    bodyZh: "<p>把密钥写在纸上，或放进你已经信任的密码管理器。不要粘贴到随机网页表单。这个本地生成器只把密钥留在当前标签页的内存里。</p>",
    faqEn: [["What alphabet is Base32?", "RFC 4648 uses A–Z and 2–7. Spaces, hyphens, and padding equals signs are stripped here."], ["Can I share a screenshot of the QR?", "A screenshot of the QR is equivalent to sharing the key. Avoid chat apps."]],
    faqZh: [["Base32 用什么字母表？", "RFC 4648 使用 A–Z 和 2–7。这里会去掉空格、连字符和填充用的等号。"], ["能把二维码截图发给别人吗？", "截图等于分享密钥。避免发到聊天软件。"]],
  },
];

export const GUIDE_ROUTES_B = guides.map(expandPage);
