import { expandPage, type CompactPage } from "./page-factory";

const guides: CompactPage[] = [
  {
    path: "/2fa-code-not-working",
    kind: "guide",
    titleEn: "2FA code not working",
    titleZh: "2FA 验证码无效时",
    titles: { "zh-tw": "2FA 驗證碼無效時", es: "El código 2FA no funciona", ja: "2FA コードが通らない", de: "2FA-Code funktioniert nicht", fr: "Code 2FA refusé", ko: "2FA 코드가 안 될 때" },
    descEn: "Clock drift, wrong digits, and algorithm mismatches that reject TOTP codes.",
    descZh: "时钟偏移、位数错误和算法不一致导致 TOTP 被拒绝。",
    h1En: "Rejected codes are usually parameters, not magic",
    h1Zh: "被拒绝的验证码通常是参数问题，不是玄学",
    introEn: "If a verifier rejects a code, check time sync, digit length, period, and SHA family before assuming the setup key is wrong.",
    introZh: "如果校验方拒绝验证码，先检查时间同步、位数、周期和 SHA 系列，再怀疑设置密钥写错。",
    bodyEn: "<p>Google-style enrollments are SHA-1, 6 digits, 30 seconds. Some enterprise IdPs ask for 8 digits or SHA-256. This generator lets you match those fields. Also wait for a fresh window; submitting a code in the last second often fails.</p>",
    bodyZh: "<p>Google 风格的登记一般是 SHA-1、6 位、30 秒。部分企业 IdP 要求 8 位或 SHA-256。本生成器可以对齐这些字段。也请等到新的时间窗；最后一秒提交经常失败。</p>",
    faqEn: [["Why does the app show a different code?", "Two devices with the same key should match if clocks agree. Compare unix time or enable automatic date settings."], ["Could spaces in the key break it?", "This decoder strips spaces and hyphens. Other stray characters are rejected."]],
    faqZh: [["为什么应用显示的码不一样？", "同一密钥的两台设备在时钟一致时应相同。请对比 unix 时间或打开自动日期。"], ["密钥里的空格会弄坏吗？", "本解码器会去掉空格和连字符。其他杂字符会被拒绝。"]],
  },
  {
    path: "/compatible-authenticator-apps",
    kind: "guide",
    showMatrix: true,
    titleEn: "Compatible authenticator apps",
    titleZh: "兼容的验证器应用",
    titles: { "zh-tw": "相容的驗證器應用", es: "Aplicaciones autenticadoras compatibles", ja: "互換のある認証アプリ", de: "Kompatible Authenticator-Apps", fr: "Applications d’authentification compatibles", ko: "호환 인증 앱" },
    descEn: "Which authenticator apps speak standard TOTP parameters.",
    descZh: "哪些验证器应用支持标准 TOTP 参数。",
    h1En: "Most authenticator apps speak the same TOTP dialect",
    h1Zh: "多数验证器应用说同一种 TOTP 方言",
    introEn: "If an app can scan an otpauth://totp/ URI, it almost certainly implements RFC 6238 with SHA-1 and 6 digits. Extra algorithms and 8-digit modes vary.",
    introZh: "只要应用能扫描 otpauth://totp/ 链接，就几乎一定实现了 SHA-1、6 位的 RFC 6238。额外算法和 8 位模式则因应用而异。",
    bodyEn: "<p>Use the table as a planning aid, not a certification. Confirm current behavior with the vendor. This site is a calculator, not a replacement for those apps.</p>",
    bodyZh: "<p>表格只是规划辅助，不是认证。请向厂商确认当前行为。本站是计算器，不能替代那些应用。</p>",
    faqEn: [["Does ChatGPT ship a generic authenticator?", "The ChatGPT apps and website offer account 2FA that you enroll with your own authenticator. They are not a drop-in Google Authenticator clone."], ["Which app is 'best'?", "The one you will back up. Open-source options like Aegis make export obvious; vendor apps may lock you to a phone."]],
    faqZh: [["ChatGPT 自带通用验证器吗？", "ChatGPT 应用和网站提供账户 2FA，需要用你自己的验证器登记。它不是即插即用的 Google Authenticator 复制品。"], ["哪个应用最好？", "你愿意备份的那个。Aegis 这类开源应用导出更明确；厂商应用可能把你锁在一部手机上。"]],
  },
  {
    path: "/test-totp-token",
    kind: "guide",
    showGenerator: true,
    titleEn: "Test a TOTP token",
    titleZh: "测试 TOTP 令牌",
    titles: { "zh-tw": "測試 TOTP 令牌", es: "Probar un token TOTP", ja: "TOTP トークンを試す", de: "TOTP-Token testen", fr: "Tester un jeton TOTP", ko: "TOTP 토큰 시험" },
    descEn: "Replay RFC 6238 Appendix B vectors or your own setup key.",
    descZh: "重放 RFC 6238 附录 B 向量，或测试你自己的设置密钥。",
    h1En: "Prove the implementation with published vectors",
    h1Zh: "用公开向量证明实现正确",
    introEn: "RFC 6238 Appendix B lists 8-digit codes for known unix times and ASCII keys. This project ships those vectors as JSON and runs them in vitest with injected time.",
    introZh: "RFC 6238 附录 B 列出了已知 unix 时间和 ASCII 密钥对应的 8 位验证码。本项目以 JSON 提供这些向量，并在 vitest 中用注入时间运行。",
    bodyEn: "<p>For a live demo, paste the Base32 form of the RFC SHA-1 key (GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ), set 8 digits, and compare against a clock that you control in tests—not against Date.now in the RFC table.</p>",
    bodyZh: "<p>现场演示可粘贴 RFC SHA-1 密钥的 Base32 形式（GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ），设为 8 位。附录表格对比的是注入时间，不是页面上的 Date.now。</p>",
    faqEn: [["Where is the JSON?", "public/rfc6238-test-vectors.json with schemaVersion 1.0."], ["Why 8 digits in the RFC?", "Appendix B uses 8 digits so truncation mistakes show up more clearly than 6-digit codes."]],
    faqZh: [["JSON 在哪？", "public/rfc6238-test-vectors.json，schemaVersion 为 1.0。"], ["RFC 为什么用 8 位？", "附录 B 用 8 位，截断错误比 6 位更容易暴露。"]],
  },
  {
    path: "/2fa-backup-codes",
    kind: "guide",
    titleEn: "2FA backup codes",
    titleZh: "2FA 备用码",
    titles: { "zh-tw": "2FA 備用碼", es: "Códigos de respaldo 2FA", ja: "2FA バックアップコード", de: "2FA-Backup-Codes", fr: "Codes de secours 2FA", ko: "2FA 백업 코드" },
    descEn: "One-time recovery strings are not TOTP and should be stored separately.",
    descZh: "一次性恢复字符串不是 TOTP，应分开保存。",
    h1En: "Backup codes are a different kind of secret",
    h1Zh: "备用码是另一种密钥",
    introEn: "Issuers print a list of single-use codes when you enable 2FA. They bypass TOTP if you lose the device. They are not generated by this HMAC tool.",
    introZh: "启用 2FA 时，发行方会打印一组一次性备用码。设备丢失时它们可以绕过 TOTP。它们不是这个 HMAC 工具生成的。",
    bodyEn: "<p>Store backup codes offline, separate from the TOTP setup key. Using one should invalidate it. If a site never showed backup codes, register a second authenticator or a hardware key while you still have access.</p>",
    bodyZh: "<p>把备用码离线存放，并与 TOTP 设置密钥分开。使用一次后应作废。如果网站从未给出备用码，趁你还能登录时再登记第二个验证器或硬件密钥。</p>",
    faqEn: [["Can this site recreate backup codes?", "No. Only the issuer can mint those strings."], ["Should I photograph them?", "A photo in a synced camera roll is another copy. Paper or a sealed password-manager note is clearer."]],
    faqZh: [["本站能重建备用码吗？", "不能。只有发行方能生成那些字符串。"], ["拍照可以吗？", "同步相册里的照片又是一份副本。纸张或密码管理器中的密封笔记更清楚。"]],
  },
  {
    path: "/2fa-secret-url",
    kind: "guide",
    titleEn: "2FA secret URLs",
    titleZh: "2FA 密钥 URL",
    titles: { "zh-tw": "2FA 金鑰 URL", es: "URL de secreto 2FA", ja: "2FA シークレット URL", de: "2FA-Geheimnis-URLs", fr: "URL de secret 2FA", ko: "2FA 비밀 URL" },
    descEn: "Fragments, query names, and path Base32 that this static site understands.",
    descZh: "本静态站点理解的片段、查询参数名和路径 Base32。",
    h1En: "Put setup keys in the fragment when you must use a URL",
    h1Zh: "必须用 URL 时，把设置密钥放进片段",
    introEn: "This site reads secret, code, key, otp, or totp from the hash first, then the query string, then a non-reserved path segment. Hash fragments are not sent to HTTP servers.",
    introZh: "本站依次从 hash、查询字符串、非保留路径段读取 secret、code、key、otp 或 totp。Hash 片段不会发给 HTTP 服务器。",
    bodyEn: "<p>Example: <code>#secret=GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ</code>. A bare fragment is treated as a key. Query and path forms are rewritten to a fragment after load so later navigations leak less. Still treat any URL with a key as sensitive.</p>",
    bodyZh: "<p>示例：<code>#secret=GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ</code>。裸片段会被当成密钥。查询和路径形式会在加载后改写为片段，减少后续导航泄露。带密钥的 URL 仍应视为敏感信息。</p>",
    faqEn: [["What paths are reserved?", "Documented pages plus robots.txt, llms.txt, sitemap*.xml, favicon, icon, og, manifest.webmanifest, rfc6238-test-vectors.json, and assets."], ["Does the URL get stored?", "Not by this app. Your browser history is another matter; clear it if you pasted a live key."]],
    faqZh: [["哪些路径是保留的？", "已文档化的页面，以及 robots.txt、llms.txt、sitemap*.xml、favicon、icon、og、manifest.webmanifest、rfc6238-test-vectors.json 和 assets。"], ["URL 会被存储吗？", "本应用不会。浏览器历史是另一回事；如果粘贴过真实密钥，请清理历史。"]],
  },
];

export const GUIDE_ROUTES_C = guides.map(expandPage);
