import { tool } from "./tool-helper";

export const TOOL_ROUTES_D = [
  tool({
    path: "/authenticator-setup-key",
    titleEn: "Authenticator setup key",
    titleZh: "验证器设置密钥",
    titles: { "zh-tw": "驗證器設定金鑰", es: "Clave de configuración del autenticador", ja: "認証アプリのセットアップキー", de: "Authenticator-Setup-Schlüssel", fr: "Clé de configuration authenticator", ko: "인증 앱 설정 키" },
    descEn: "Type or paste an authenticator setup key to see live codes.",
    descZh: "输入或粘贴验证器设置密钥以查看实时验证码。",
    h1En: "The setup key is Base32, not the six-digit code",
    h1Zh: "设置密钥是 Base32，不是那六位数字",
    introEn: "Issuers label it 'setup key', 'secret key', or 'can't scan the QR?'. It is a Base32 string. Paste it here to confirm you copied it before you close the enrollment dialog.",
    introZh: "发行方会把它标成“设置密钥”、“密钥”或“无法扫描二维码？”。它是 Base32 字符串。在关闭登记对话框前，可贴到这里确认复制是否正确。",
    bodyEn: "<p>Maximum length after stripping spaces, hyphens, and padding is 256 characters. Other alphabets are rejected so a mistyped character cannot silently yield the wrong account.</p>",
    bodyZh: "<p>去掉空格、连字符和填充后最长 256 个字符。其他字母表会被拒绝，避免打错一个字符却默默对应到错误账户。</p>",
    q1e: "Lowercase allowed?", a1e: "Yes. Input is uppercased before decode.",
    q2e: "Padding equals?", a2e: "Stripped. You do not need to add = signs.",
    q3e: "Is the key stored?", a3e: "Only in memory on this card, never in localStorage.",
    q1z: "允许小写吗？", a1z: "允许。解码前会转成大写。",
    q2z: "填充等号呢？", a2z: "会去掉。你不必补 =。",
    q3z: "密钥会存储吗？", a3z: "只在这张卡片的内存里，绝不进入 localStorage。",
  }),
  tool({
    path: "/2fa-qr-code-setup-key",
    titleEn: "2FA QR code setup key",
    titleZh: "2FA 二维码设置密钥",
    titles: { "zh-tw": "2FA QR 設定金鑰", es: "Clave de configuración del QR 2FA", ja: "2FA QR のセットアップキー", de: "2FA-QR-Setup-Schlüssel", fr: "Clé du QR 2FA", ko: "2FA QR 설정 키" },
    descEn: "Turn a 2FA QR payload or its printed setup key into codes.",
    descZh: "把 2FA 二维码内容或其打印的设置密钥变成验证码。",
    h1En: "A 2FA QR code is usually an otpauth URI",
    h1Zh: "2FA 二维码通常是 otpauth 链接",
    introEn: "When you cannot scan, issuers print the URI or the Base32 key. Either can be pasted. Scan QR image uses BarcodeDetector on a file you choose.",
    introZh: "无法扫描时，发行方会打印 URI 或 Base32 密钥。两者都能粘贴。扫描二维码图片会用 BarcodeDetector 处理你选择的文件。",
    bodyEn: "<p>If BarcodeDetector is missing, the status region tells you to paste instead. No image leaves the machine.</p>",
    bodyZh: "<p>如果缺少 BarcodeDetector，状态区会提示你改为粘贴。图片不会离开本机。</p>",
    q1e: "Camera live scan?", a1e: "Not in this version. Pick an image file of the QR.",
    q2e: "PNG and JPEG?", a2e: "Any image/* the browser can decode.",
    q3e: "Multiple QR codes?", a3e: "The first detected payload is used.",
    q1z: "实时摄像头扫描？", a1z: "此版本没有。请选择二维码图片文件。",
    q2z: "支持 PNG 和 JPEG 吗？", a2z: "浏览器能解码的任何 image/*。",
    q3z: "多个二维码？", a3z: "使用检测到的第一段内容。",
  }),
  tool({
    path: "/cannot-scan-2fa-qr-code",
    titleEn: "Cannot scan 2FA QR code",
    titleZh: "无法扫描 2FA 二维码",
    titles: { "zh-tw": "無法掃描 2FA QR", es: "No puedo escanear el QR 2FA", ja: "2FA QR をスキャンできない", de: "2FA-QR nicht scannbar", fr: "Impossible de scanner le QR 2FA", ko: "2FA QR을 스캔할 수 없음" },
    descEn: "Fallback when a phone camera cannot read an enrollment QR.",
    descZh: "手机摄像头读不了登记二维码时的退路。",
    h1En: "If you cannot scan, type the setup key",
    h1Zh: "无法扫描就输入设置密钥",
    introEn: "Desktop enrollment pages often show a QR that a laptop webcam will not scan. Copy the 'enter this key manually' string instead of fighting the camera.",
    introZh: "桌面登记页上的二维码常常无法用笔记本摄像头扫描。请复制“手动输入此密钥”字符串，不必和摄像头较劲。",
    bodyEn: "<p>Glare, cropped screenshots, and inverted colors all break scanners. Paste wins. If the issuer never showed a key, screenshot the QR and use Scan QR image on a phone browser that implements BarcodeDetector.</p>",
    bodyZh: "<p>反光、裁切截图和反色都会让扫描失败。粘贴更稳。如果发行方从未显示密钥，请截取二维码，在实现了 BarcodeDetector 的手机浏览器里用“扫描二维码图片”。</p>",
    q1e: "Blurry projector QR?", a1e: "Ask for the manual key. Do not trust a reconstructed Base32 guess.",
    q2e: "QR is otpauth-hotp?", a2e: "This tool refuses HOTP URIs. Ask the issuer for TOTP.",
    q3e: "Dark mode inverted QR?", a3e: "Capture against a light background or paste the key.",
    q1z: "投影模糊的二维码？", a1z: "要手动密钥。不要信任猜出来的 Base32。",
    q2z: "二维码是 otpauth-hotp？", a2z: "本工具拒绝 HOTP 链接。请向发行方要 TOTP。",
    q3z: "暗色模式下反色二维码？", a3z: "在浅色背景上截取，或直接粘贴密钥。",
  }),
  tool({
    path: "/otpauth-qr-code-reader",
    titleEn: "otpauth QR code reader",
    titleZh: "otpauth 二维码读取器",
    titles: { "zh-tw": "otpauth QR 讀取器", es: "Lector de QR otpauth", ja: "otpauth QR リーダー", de: "otpauth-QR-Leser", fr: "Lecteur QR otpauth", ko: "otpauth QR 리더" },
    descEn: "Read otpauth://totp/ payloads from a QR image in the browser.",
    descZh: "在浏览器中从二维码图片读取 otpauth://totp/ 内容。",
    h1En: "Decode otpauth from a QR without a backend",
    h1Zh: "无需后端，从二维码解码 otpauth",
    introEn: "Choose a QR image. If the payload is otpauth://totp/..., the generator fills secret, algorithm, digits, period, and name from issuer or label.",
    introZh: "选择一张二维码图片。如果内容是 otpauth://totp/…，生成器会填入密钥、算法、位数、周期，以及来自发行方或标签的名称。",
    bodyEn: "<p>Non-otpauth payloads that look like Base32 are treated as raw setup keys. Other URI schemes are ignored besides reporting that a QR was found.</p>",
    bodyZh: "<p>看起来像 Base32 的非 otpauth 内容会当作原始设置密钥。其他 URI 方案除了提示找到二维码外会被忽略。</p>",
    q1e: "Does reading upload the image?", a1e: "No. BarcodeDetector runs locally.",
    q2e: "Encrypted QR?", a2e: "Not supported. Only standard otpauth or Base32 text.",
    q3e: "Migration QR from Google?", a3e: "otpauth-migration payloads are not decoded here. Export individual otpauth URIs instead.",
    q1z: "读取会上传图片吗？", a1z: "不会。BarcodeDetector 在本地运行。",
    q2z: "加密二维码？", a2z: "不支持。只有标准 otpauth 或 Base32 文本。",
    q3z: "Google 的迁移二维码？", a3z: "这里不解 otpauth-migration。请改为导出单条 otpauth 链接。",
  }),
];
