import { tool } from "./tool-helper";

export const TOOL_ROUTES_C = [
  tool({
    path: "/time-based-one-time-password-generator",
    titleEn: "Time-based one-time password generator",
    titleZh: "基于时间的一次性密码生成器",
    titles: { "zh-tw": "基於時間的一次性密碼產生器", es: "Generador de contraseñas de un solo uso basadas en tiempo", ja: "時間ベースワンタイムパスワード生成", de: "Zeitbasiertes Einmalpasswort", fr: "Générateur de mot de passe à usage unique temporel", ko: "시간 기반 일회용 비밀번호 생성기" },
    descEn: "Generate time-based one-time passwords from a shared Base32 key.",
    descZh: "由共享 Base32 密钥生成基于时间的一次性密码。",
    h1En: "Time is the moving factor you cannot see",
    h1Zh: "时间是你看不见的移动因子",
    introEn: "A time-based one-time password is HMAC(key, timestamp_counter). This page shows the resulting digits and how many seconds remain in the current period.",
    introZh: "基于时间的一次性密码是 HMAC(key, timestamp_counter)。本页显示结果数字以及当前周期还剩多少秒。",
    bodyEn: "<p>Period defaults to 30 and can be set from 10 to 120 in steps of 5. Custom periods only work if the verifier uses the same number.</p>",
    bodyZh: "<p>周期默认 30，可在 10 到 120 之间以 5 为步进调整。只有校验方使用相同数字时，自定义周期才有效。</p>",
    q1e: "What is unix time here?", a1e: "Seconds since 1970-01-01 UTC, divided by the period, floored.",
    q2e: "Leap seconds?", a2e: "Ignored, as in typical TOTP libraries.",
    q3e: "Timezone?", a3e: "UTC. Local timezone offsets do not enter the HMAC.",
    q1z: "这里的 unix 时间是什么？", a1z: "从 1970-01-01 UTC 起的秒数，除以周期后向下取整。",
    q2z: "闰秒呢？", a2z: "忽略，和常见 TOTP 库一样。",
    q3z: "时区呢？", a3z: "UTC。本地时区偏移不进入 HMAC。",
  }),
  tool({
    path: "/google-authenticator-code-generator",
    titleEn: "Google Authenticator code generator",
    titleZh: "Google Authenticator 验证码生成器",
    titles: { "zh-tw": "Google Authenticator 驗證碼產生器", es: "Generador de códigos de Google Authenticator", ja: "Google Authenticator コード生成", de: "Google-Authenticator-Codegenerator", fr: "Générateur de codes Google Authenticator", ko: "Google Authenticator 코드 생성기" },
    descEn: "Compute Google Authenticator-style TOTP codes locally from a setup key.",
    descZh: "根据设置密钥在本地计算 Google Authenticator 风格的 TOTP 验证码。",
    h1En: "Google Authenticator style means SHA-1 and six digits",
    h1Zh: "Google Authenticator 风格意味着 SHA-1 和六位数字",
    introEn: "This is not the Google Authenticator application. It uses the same default TOTP parameters that app historically applied to otpauth URIs: HMAC-SHA1, 6 digits, 30 seconds.",
    introZh: "这不是 Google Authenticator 应用。它使用该应用历史上对 otpauth 链接采用的默认 TOTP 参数：HMAC-SHA1、6 位、30 秒。",
    bodyEn: "<p>If Google Authenticator on your phone shows a different code, check clock sync and that you typed the same Base32 key. Recent app versions may expose extra options; match them in TOTP options.</p>",
    bodyZh: "<p>如果手机上的 Google Authenticator 显示不同验证码，请检查时钟同步以及 Base32 密钥是否相同。较新版本可能提供额外选项；请在 TOTP 选项中对齐。</p>",
    q1e: "Do you connect to Google?", a1e: "No Google API calls are made.",
    q2e: "Export QR from the official app?", a2e: "Use Google's own transfer flow. This page only accepts a key or otpauth URI you already have.",
    q3e: "Accounts.google.com enrollment?", a3e: "Finish enrollment in Google's UI. This generator is for later code display.",
    q1z: "会连接 Google 吗？", a1z: "不会发起任何 Google API 调用。",
    q2z: "能从官方应用导出二维码吗？", a2z: "请用 Google 自己的转移流程。本页只接受你已有的密钥或 otpauth 链接。",
    q3z: "Accounts.google.com 登记呢？", a3z: "请在 Google 界面完成登记。本生成器用于之后显示验证码。",
  }),
  tool({
    path: "/microsoft-authenticator-code-generator",
    titleEn: "Microsoft Authenticator code generator",
    titleZh: "Microsoft Authenticator 验证码生成器",
    titles: { "zh-tw": "Microsoft Authenticator 驗證碼產生器", es: "Generador de códigos de Microsoft Authenticator", ja: "Microsoft Authenticator コード生成", de: "Microsoft-Authenticator-Codegenerator", fr: "Générateur de codes Microsoft Authenticator", ko: "Microsoft Authenticator 코드 생성기" },
    descEn: "Local TOTP codes compatible with Microsoft Authenticator style entries.",
    descZh: "与 Microsoft Authenticator 风格条目兼容的本地 TOTP 验证码。",
    h1En: "Microsoft work accounts may still be standard TOTP",
    h1Zh: "Microsoft 工作账户仍可能是标准 TOTP",
    introEn: "Microsoft Authenticator can store TOTP entries alongside push-based Microsoft account approvals. This page only reproduces the TOTP half, using a setup key you already exported or typed.",
    introZh: "Microsoft Authenticator 可以在推送式 Microsoft 账户批准之外保存 TOTP 条目。本页只重现 TOTP 这一半，使用你已导出或输入的设置密钥。",
    bodyEn: "<p>Number matching and passwordless phone sign-in are not TOTP and cannot be calculated here. If Azure AD/Entra shows a QR during software token setup, the payload is still an otpauth URI you can paste.</p>",
    bodyZh: "<p>数字匹配和无密码手机登录不是 TOTP，无法在此计算。若 Azure AD/Entra 在软件令牌设置时显示二维码，其内容仍是可粘贴的 otpauth 链接。</p>",
    q1e: "Is this the Microsoft app?", a1e: "No. It does not talk to Microsoft identity platforms.",
    q2e: "Push approve a login?", a2e: "Impossible here. Open the official Microsoft Authenticator for push.",
    q3e: "8-digit Microsoft tokens?", a3e: "Switch digits to 8 in TOTP options if your directory requires it.",
    q1z: "这是微软官方应用吗？", a1z: "不是。它不会连接 Microsoft 身份平台。",
    q2z: "能推送批准登录吗？", a2z: "这里做不到。推送请打开官方 Microsoft Authenticator。",
    q3z: "微软的 8 位令牌？", a3z: "如果目录要求 8 位，请在 TOTP 选项中切换。",
  }),
  tool({
    path: "/mfa-code-generator",
    titleEn: "MFA code generator",
    titleZh: "MFA 验证码生成器",
    titles: { "zh-tw": "MFA 驗證碼產生器", es: "Generador de códigos MFA", ja: "MFA コード生成", de: "MFA-Codegenerator", fr: "Générateur de codes MFA", ko: "MFA 코드 생성기" },
    descEn: "Generate the MFA TOTP code used as a second factor.",
    descZh: "生成作为第二因素的 MFA TOTP 验证码。",
    h1En: "MFA codes from this page are TOTP possession codes",
    h1Zh: "本页的 MFA 验证码是 TOTP 持有码",
    introEn: "Enterprise language says MFA; the moving code is still TOTP more often than not. Feed the software-token key into the generator rather than a hardware serial number.",
    introZh: "企业用语常说 MFA；滚动的码多半仍是 TOTP。请把软件令牌密钥送进生成器，而不是硬件序列号。",
    bodyEn: "<p>FIDO2/WebAuthn is a different factor. If a site offers both, prefer the security key for phishing resistance and keep TOTP as backup if policy allows.</p>",
    bodyZh: "<p>FIDO2/WebAuthn 是另一种因素。如果网站两者都提供，为了抗钓鱼请优先安全密钥，并在策略允许时把 TOTP 当备份。</p>",
    q1e: "RSA SecurID?", a1e: "Usually not compatible. Those tokens use vendor algorithms.",
    q2e: "Okta / Duo?", a2e: "If enrollment showed a standard QR, paste the otpauth URI. Duo push is separate.",
    q3e: "Policy require 8 digits?", a3e: "Yes—set digits to 8. Defaults stay at 6.",
    q1z: "RSA SecurID？", a1z: "通常不兼容。那些令牌使用厂商算法。",
    q2z: "Okta / Duo？", a2z: "如果登记时是标准二维码，粘贴 otpauth 链接。Duo 推送是另一回事。",
    q3z: "策略要求 8 位？", a3z: "可以，把位数设为 8。默认仍是 6。",
  }),
];
